/*
 * Generate a permission for every one of our app commands (#143).
 *
 * Without an app manifest, Tauri **lets app commands from a local origin through with no
 * permission check at all.** The check only fires under three conditions: the command is a
 * plugin command, the app has declared a manifest, or the request came from a remote origin
 * (tauri 2.11.5 webview/mod.rs `on_message`,
 * `plugin_command.is_some() || has_app_acl_manifest || !is_local`). So until now, a page on a
 * local origin (the dev server address, `tauri://localhost`, or a registered custom scheme)
 * could call any registered command from any window and any frame. The only thing standing
 * in the way was the invoke key, which changes on every run, and Tauri writes the real key to
 * stderr whenever the key is wrong.
 *
 * Every command listed in `commands` gets an `allow-<command>` and `deny-<command>`
 * permission (underscores become hyphens, written as files under
 * `permissions/autogenerated/`). From the moment a manifest exists, every app command goes
 * through a permission check. The place that actually grants the permission is
 * `capabilities/default.json`, which grants it only to the local origin of the `main` window.
 *
 * This list has to match `invoke_handler` in lib.rs. A command missing here has no permission
 * and nobody can call it; a command missing there has a permission but no handler.
 * tooling/desktop-permissions.test.ts checks that the two agree.
 */
fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "host_info",
            "host_error",
            "restart_host",
            "set_badge",
            "alert",
            "open_in_ide",
            "reveal_path",
            "trash_path",
            "file_manager_name",
            "focus_window",
            "window_controls_inset",
            "shortcut_keys",
            "quit_app",
            "take_app_links",
            "host_build",
            "switch_host_build",
            "background_mode",
            "set_background_mode",
            "quit_and_stop_agents",
        ]),
    ))
    .expect("failed to run tauri-build");
}
