/*
 * 우리 앱 명령마다 권한을 만든다 (#143).
 *
 * 앱 매니페스트가 없으면 Tauri는 **로컬 출처에서 온 앱 명령을 권한 검사 없이 통과시킨다.**
 * 검사가 걸리는 조건은 셋이다: 플러그인 명령이거나, 앱이 매니페스트를 선언했거나, 요청이 원격
 * 출처에서 왔거나 (tauri 2.11.5 webview/mod.rs `on_message`,
 * `plugin_command.is_some() || has_app_acl_manifest || !is_local`). 그래서 지금까지는 로컬
 * 출처(개발 서버 주소, `tauri://localhost`, 등록한 사용자 정의 스킴)의 페이지라면 어느 창의
 * 어느 프레임이든 등록한 명령을 모두 부를 수 있었다. 막는 것은 실행마다 바뀌는 invoke 키
 * 하나였고, Tauri는 키가 틀릴 때마다 진짜 키를 표준에러에 쓴다.
 *
 * `commands`에 적은 명령마다 `allow-<명령>`·`deny-<명령>` 권한이 생긴다(밑줄은 하이픈으로,
 * `permissions/autogenerated/`에 파일로). 매니페스트가 생기는 순간부터 모든 앱 명령이 권한
 * 검사를 탄다. 실제로 권한을 주는 곳은 `capabilities/default.json`이다. 창 `main`의 로컬
 * 출처에만 준다.
 *
 * 이 목록은 lib.rs의 `invoke_handler`와 같아야 한다. 여기 없는 명령은 권한이 없어 아무도 못
 * 부르고, 거기 없는 명령은 권한이 있어도 처리기가 없다. tooling/desktop-permissions.test.ts가
 * 둘을 맞춰 본다.
 */
fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "host_info",
            "host_error",
            "restart_host",
            "set_badge",
            "alert",
            "open_in_ide",
            "reveal_path",
            "trash_path",
            "file_manager_name",
            "focus_window",
            "window_controls_inset",
            "shortcut_keys",
            "quit_app",
            "take_app_links",
        ]),
    ))
    .expect("failed to run tauri-build");
}
