// Project board — this app's MCP server. Centralu starts it (`node server.mjs`, stdio) when it is first
// needed and restarts it after the builder's turn when this folder changed.
// Edit this file, github.mjs and ui/index.html freely. Never edit runtime/ (generated by Centralu).
// Read AGENTS.md for the rules.
//
// The board is the GitHub Project named in project.json. GitHub is the only copy: every read asks
// GitHub (through the person's own `gh`, see github.mjs), with an in-memory cache of a few seconds,
// and every write goes straight to GitHub and is read back before the tool answers.
import { readFile } from 'node:fs/promises'
import { McpServer, serveStdio, z, centralu } from './runtime/centralu-app-runtime.mjs'
import { GitHubError, addContent, findContent, parseItemRef, readBoard, resolveOption, sameRepo, setOption } from './github.mjs'

const UI = 'ui://project-board/index.html'

const config = await readFile(new URL('./project.json', import.meta.url), 'utf8')
  .then((t) => JSON.parse(t))
  .catch((e) => {
    console.error(`project.json could not be read: ${e.message}`)
    process.exit(1)
  })
for (const key of ['owner', 'number', 'repository', 'fields', 'decisionStatus']) {
  if (config[key] === undefined) {
    console.error(`project.json is missing "${key}"`)
    process.exit(1)
  }
}
const CACHE_MS = Math.max(0, Number(config.cacheSeconds ?? 30)) * 1000

// --- The short cache -------------------------------------------------------------------------------
// One board in memory, for at most CACHE_MS. A write forgets it, and a read that started before a
// write never refills it (the generation check), so a tool never answers from a board older than
// its own last write.
let cache = null
let generation = 0
let inflight = null

async function board({ fresh = false } = {}) {
  if (!fresh && cache && cache.generation === generation && Date.now() - cache.at < CACHE_MS) return cache.board
  if (inflight && inflight.generation === generation) return inflight.promise
  const started = generation
  const promise = readBoard(config).then((b) => {
    if (started === generation) cache = { board: b, at: Date.now(), generation: started }
    return b
  })
  inflight = { generation: started, promise }
  promise.finally(() => {
    if (inflight?.promise === promise) inflight = null
  }).catch(() => {})
  return promise
}
const forget = () => {
  generation += 1
  cache = null
}

// --- One write at a time ---------------------------------------------------------------------------
// An agent may send several calls at once (a live Claude session sent both halves of a round trip
// in parallel). Each write reads the item fresh, so running them in arrival order keeps every
// "from → to" true and the last call the one that wins.
let writes = Promise.resolve()
function oneAtATime(fn) {
  const run = writes.then(fn, fn)
  writes = run.catch(() => {})
  return run
}

// --- Presenting ------------------------------------------------------------------------------------
const TYPE = { issue: 'issue', pull: 'pull request', draft: 'draft issue', hidden: 'hidden item' }
const ref = (item) => (item.number == null ? TYPE[item.type] : sameRepo(item.repository, config.repository) ? `#${item.number}` : `${item.repository}#${item.number}`)
const label = (item) => `${ref(item)} ${item.title}`
const facts = (item) =>
  [`Status ${item.status ?? '(none)'}`, `Priority ${item.priority ?? '(none)'}`, `Area ${item.area ?? '(none)'}`].join(' · ')
const line = (item) =>
  `- ${label(item)} — Priority ${item.priority ?? '(none)'} · Area ${item.area ?? '(none)'} · ${item.draft ? 'draft ' : ''}${TYPE[item.type]}${item.url ? ` · ${item.url}` : ''}`

/** Status columns in the project's own order, with the decision column first. */
function columns(b) {
  const names = b.fields.status.options.map((o) => o.name)
  const first = names.find((n) => n.toLowerCase() === String(config.decisionStatus).toLowerCase())
  return first ? [first, ...names.filter((n) => n !== first)] : names
}
const where = (b) => `${b.project.title} (GitHub Project #${b.project.number} of ${b.project.owner}), read from GitHub at ${b.fetchedAt}`
const RANK = { High: 0, Medium: 1, Low: 2 }
const byPriority = (a, b) => (RANK[a.priority] ?? 3) - (RANK[b.priority] ?? 3) || (a.number ?? 0) - (b.number ?? 0)

/**
 * One answer: the text, and the same words first in structuredContent (`summary`). A session's
 * client may hand the model the structured part instead of the text (Claude Code does, seen in a
 * live session), and what a write changed must reach the model either way.
 */
const answer = (t, structured, summary = t) => ({ content: [{ type: 'text', text: t }], structuredContent: { summary, ...structured } })

/** A failure as an answer: the message says what happened and what to do, and nothing changed. */
function failure(e, prefix = '') {
  const known = e instanceof GitHubError
  const message = `${prefix}${known ? e.message : `Unexpected error: ${e?.message ?? e}`}`
  if (!known) console.error(e)
  return { isError: true, ...answer(message, { error: { kind: known ? e.kind : 'internal', message } }) }
}

function findItem(b, input) {
  const want = parseItemRef(input, config.repository)
  const item = b.items.find((i) => i.number === want.number && sameRepo(i.repository, want.repo))
  return { want, item }
}

/**
 * Applies status/priority/area to one item, one field at a time, skipping a field that already has
 * the value. All names are checked before the first write. A failed write carries what was done.
 */
async function applyFields(b, item, changes) {
  const plan = []
  for (const key of ['status', 'priority', 'area']) {
    if (changes[key] === undefined) continue
    const field = b.fields[key]
    const option = resolveOption(field, changes[key])
    plan.push({ key, field, option, from: item[key] })
  }
  const done = []
  const unchanged = []
  for (const p of plan) {
    if (p.from === p.option.name) {
      unchanged.push(`${p.field.name} was already ${p.option.name}`)
      continue
    }
    try {
      await setOption(b.project.id, item.itemId, p.field.id, p.option.id)
    } catch (e) {
      e.done = done
      throw e
    } finally {
      // Whether or not this write landed, the cached board can no longer be trusted.
      forget()
    }
    done.push({ field: p.field.name, from: p.from, to: p.option.name })
  }
  return { done, unchanged, plan }
}

const describeDone = (done) => done.map((d) => `- ${d.field}: ${d.from ?? '(none)'} → ${d.to}`).join('\n')

/**
 * GitHub can take a moment to list an item that was just added: on 2026-10-04 the read right after
 * `addProjectV2ItemById` came back without it four times in a row, and a second read a few seconds
 * later had it. So a read that looks for one item tries a few times, with short waits.
 */
const LIST_WAITS_MS = [0, 500, 1000, 1500, 2000]
async function findFresh(itemId) {
  let last
  for (const ms of LIST_WAITS_MS) {
    if (ms) await new Promise((r) => setTimeout(r, ms))
    last = await board({ fresh: true })
    const item = last.items.find((i) => i.itemId === itemId)
    if (item) return { board: last, item }
  }
  return { board: last, item: null }
}

/**
 * Reads the item again, fresh, and says what GitHub now shows (and whether it matches). It never
 * throws: by now something may have been written, and a failed read must not hide that.
 */
async function readBack(itemId, plan) {
  let item
  try {
    ;({ item } = await findFresh(itemId))
  } catch (e) {
    return { item: null, text: `Reading it back from GitHub failed: ${e?.message ?? e}` }
  }
  if (!item) return { item: null, text: 'Reading it back, GitHub did not list the item in the project.' }
  const off = plan.filter((p) => item[p.key] !== p.option.name).map((p) => `${p.field.name} is ${item[p.key] ?? '(none)'}, not ${p.option.name}`)
  return {
    item,
    text: `GitHub now shows ${ref(item)}: ${facts(item)}.${off.length ? ` Warning: ${off.join('; ')}.` : ''}`,
  }
}

const fieldInputs = {
  status: z.string().optional().describe('New Status, for example "Ready" or "In review"'),
  priority: z.string().optional().describe('New Priority: High, Medium or Low'),
  area: z.string().optional().describe('New Area, for example "UI" or "Apps"'),
}

// The two writes. Registered below; each runs inside oneAtATime.
async function setItemFields({ item: input, status, priority, area }) {
  if (status === undefined && priority === undefined && area === undefined)
    return failure(new GitHubError('input', 'Nothing to change: give at least one of status, priority or area.'))
  let target = null
  try {
    const b = await board({ fresh: true })
    const { want, item } = findItem(b, input)
    if (!item)
      throw new GitHubError('input', `${want.repo}#${want.number} is not in the project ${b.project.title}. Nothing changed. Add it first with add_item.`)
    target = item
    const { done, unchanged, plan } = await applyFields(b, item, { status, priority, area })
    const back = await readBack(item.itemId, plan)
    const parts = [
      done.length ? `Changed on GitHub, project ${b.project.title}: ${label(item)}\n${describeDone(done)}` : `Nothing changed on GitHub for ${label(item)}.`,
      ...(unchanged.length ? [`Unchanged: ${unchanged.join('; ')}.`] : []),
      back.text,
    ]
    return answer(parts.join('\n'), { changed: done, item: back.item ?? item })
  } catch (e) {
    const done = e?.done ?? []
    const prefix = target
      ? done.length
        ? `Partly changed on GitHub for ${label(target)}:\n${describeDone(done)}\nThen it failed: `
        : `Nothing changed for ${label(target)}. `
      : ''
    return failure(e, prefix)
  }
}

async function addItem({ item: input, status, priority, area }) {
  const parts = []
  try {
    const want = parseItemRef(input, config.repository)
    const b = await board({ fresh: true })
    // Option names are checked before anything is written.
    for (const key of ['status', 'priority', 'area']) if ({ status, priority, area }[key] !== undefined) resolveOption(b.fields[key], { status, priority, area }[key])
    let item = b.items.find((i) => i.number === want.number && sameRepo(i.repository, want.repo))
    let current = b
    if (item) {
      parts.push(`Already in the project ${b.project.title}: ${label(item)}. Nothing added.`)
    } else {
      const content = await findContent(want.repo, want.number)
      if (!content) throw new GitHubError('input', `${want.repo}#${want.number} is not an issue or pull request this GitHub login can see. Nothing added.`)
      const itemId = await addContent(b.project.id, content.id)
      forget()
      parts.push(`Added to the project ${b.project.title} on GitHub: ${TYPE[content.type]} ${ref({ ...content, repository: want.repo })} ${content.title} (${content.url}).`)
      ;({ board: current, item } = await findFresh(itemId))
      if (!item) throw new GitHubError('github', 'GitHub accepted the item but did not list it when read back. Refresh in a moment.')
    }
    let plan = []
    if (status !== undefined || priority !== undefined || area !== undefined) {
      const r = await applyFields(current, item, { status, priority, area })
      plan = r.plan
      if (r.done.length) parts.push(`Then set:\n${describeDone(r.done)}`)
      if (r.unchanged.length) parts.push(`Unchanged: ${r.unchanged.join('; ')}.`)
    }
    const back = await readBack(item.itemId, plan)
    parts.push(back.text)
    return answer(parts.join('\n'), { item: back.item ?? item })
  } catch (e) {
    return failure(e, parts.length ? `${parts.join('\n')}\nThen it failed: ` : '')
  }
}

serveStdio(() => {
  const server = new McpServer({ name: 'project-board', version: '0.1.0' }, { capabilities: { tools: {}, resources: {} } })

  centralu.uiResource(server, 'board', UI, new URL('./ui/index.html', import.meta.url))

  // The home tool: the screen's whole state, read from GitHub. It answers a failure as data rather
  // than isError, so the screen states the reason (GitHub unreachable, gh missing, scope missing)
  // instead of showing an empty board, and an outage is not filed as a bug in the app.
  centralu.tool(
    server,
    'show',
    {
      title: 'Show the board',
      description: 'Open the board and return the project, its Status/Priority/Area options and its items.',
      inputSchema: z.object({ refresh: z.boolean().optional().describe('Skip the short cache and ask GitHub now') }),
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { ui: { resourceUri: UI, visibility: ['app'] } },
    },
    async ({ refresh }) => {
      try {
        const b = await board({ fresh: refresh === true })
        return answer(`${b.items.length} items. ${where(b)}.`, {
          ok: true,
          project: b.project,
          columns: columns(b),
          decisionStatus: config.decisionStatus,
          options: { status: b.fields.status.options.map((o) => o.name), priority: b.fields.priority.options.map((o) => o.name), area: b.fields.area.options.map((o) => o.name) },
          items: b.items,
          fetchedAt: b.fetchedAt,
        })
      } catch (e) {
        const f = failure(e)
        return { content: f.content, structuredContent: { ok: false, ...f.structuredContent } }
      }
    },
  )

  centralu.tool(
    server,
    'list_items',
    {
      title: 'List project items',
      description:
        'List the items of the Centralu GitHub Project, grouped by Status in board order, read from GitHub. Optionally filter by status, area and priority.',
      inputSchema: z.object({
        status: z.string().optional().describe('Only this Status, for example "Ready"'),
        area: z.string().optional().describe('Only this Area, for example "UI"'),
        priority: z.string().optional().describe('Only this Priority: High, Medium or Low'),
      }),
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ status, area, priority }) => {
      try {
        const b = await board()
        const want = {
          status: status === undefined ? null : resolveOption(b.fields.status, status).name,
          area: area === undefined ? null : resolveOption(b.fields.area, area).name,
          priority: priority === undefined ? null : resolveOption(b.fields.priority, priority).name,
        }
        const items = b.items.filter((i) => (!want.status || i.status === want.status) && (!want.area || i.area === want.area) && (!want.priority || i.priority === want.priority))
        const filters = Object.entries(want).filter(([, v]) => v).map(([k, v]) => `${b.fields[k].name} ${v}`)
        const cols = want.status ? [want.status] : [...columns(b), ...(items.some((i) => !i.status) ? [null] : [])]
        const ordered = []
        const blocks = cols.map((c) => {
          const inCol = items.filter((i) => i.status === c).sort(byPriority)
          ordered.push(...inCol)
          return `${c ?? 'No status'} (${inCol.length})\n${inCol.length ? inCol.map(line).join('\n') : '- none'}`
        })
        const head = `${where(b)}. ${items.length} of ${b.items.length} items${filters.length ? `, filtered by ${filters.join(', ')}` : ''}.`
        return answer(`${head}\n\n${blocks.join('\n\n')}`, { project: b.project, columns: cols, filters: want, items: ordered, fetchedAt: b.fetchedAt }, head)
      } catch (e) {
        return failure(e)
      }
    },
  )

  centralu.tool(
    server,
    'list_needs_decision',
    {
      title: 'List items that need a decision',
      description: `List the items whose Status is "${config.decisionStatus}": the decisions waiting on the owner, highest priority first. Optionally only one Area.`,
      inputSchema: z.object({ area: z.string().optional().describe('Only this Area, for example "UI"') }),
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ area }) => {
      try {
        const b = await board()
        const decision = resolveOption(b.fields.status, config.decisionStatus).name
        const wantArea = area === undefined ? null : resolveOption(b.fields.area, area).name
        const items = b.items.filter((i) => i.status === decision && (!wantArea || i.area === wantArea)).sort(byPriority)
        const head = `${where(b)}. ${items.length} item${items.length === 1 ? '' : 's'} with Status ${decision}${wantArea ? ` in Area ${wantArea}` : ''}.`
        return answer(items.length ? `${head}\n\n${items.map(line).join('\n')}` : head, { project: b.project, status: decision, area: wantArea, items, fetchedAt: b.fetchedAt }, head)
      } catch (e) {
        return failure(e)
      }
    },
  )

  // Writes. Visible to agents and to the screen (the board's status menu and drag call this one), so
  // both go through the same code. Every answer names what changed on GitHub, then what GitHub shows.
  centralu.tool(
    server,
    'set_item_fields',
    {
      title: 'Set Status, Priority or Area',
      description:
        'Set the Status, Priority and/or Area of one item of the Centralu GitHub Project, on GitHub. The item is an issue or pull request already in the project: a number such as 8 or #8 (this repository), owner/repo#8, or its URL. Says what changed and what GitHub shows afterwards.',
      inputSchema: z.object({ item: z.union([z.string(), z.number()]).describe('Issue or pull request: 8, "#8", "owner/repo#8" or its URL'), ...fieldInputs }),
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    (args) => oneAtATime(() => setItemFields(args)),
  )

  centralu.tool(
    server,
    'add_item',
    {
      title: 'Add an issue or pull request to the project',
      description:
        'Add an issue or pull request to the Centralu GitHub Project, on GitHub, by number (8 or #8 for this repository, owner/repo#8) or URL, and optionally set its Status, Priority and Area. Says what was added and what GitHub shows afterwards. An item already in the project is not added twice.',
      inputSchema: z.object({ item: z.union([z.string(), z.number()]).describe('Issue or pull request: 8, "#8", "owner/repo#8" or its URL'), ...fieldInputs }),
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
      _meta: { ui: { visibility: ['model'] } },
    },
    (args) => oneAtATime(() => addItem(args)),
  )

  return server
})
