// Project board — this app's MCP server. Centralu starts it (`node server.mjs`, stdio) when it is first
// needed and restarts it after the builder's turn when this folder changed.
// Edit this file, github.mjs and ui/index.html freely. Never edit runtime/ (generated by Centralu).
// Read AGENTS.md for the rules.
//
// The board is the GitHub Project named in project.json. GitHub is the only copy: every read asks
// GitHub (through the person's own `gh`, see github.mjs), with an in-memory cache of a few seconds,
// and every write goes straight to GitHub and is read back before the tool answers.
import { readFile } from 'node:fs/promises'
import { McpServer, serveStdio, z, centralu } from './runtime/centralu-app-runtime.mjs'
import {
  GitHubError,
  addContent,
  deleteBranch,
  findContent,
  mergePr,
  parseItemRef,
  readBoard,
  readChecks,
  readIssueText,
  readJobLog,
  readPr,
  readRepo,
  readRequired,
  resolveOption,
  resolveRef,
  sameRepo,
  setOption,
} from './github.mjs'
import { NO_PERMISSION, canMerge, clip, decideMerge, evaluateChecks, firstFailure, matchKnownFailure, squashMessage, workflowCheckNames } from './ci.mjs'

const UI = 'ui://project-board/index.html'

const config = await readFile(new URL('./project.json', import.meta.url), 'utf8')
  .then((t) => JSON.parse(t))
  .catch((e) => {
    console.error(`project.json could not be read: ${e.message}`)
    process.exit(1)
  })
for (const key of ['owner', 'number', 'repository', 'fields', 'decisionStatus']) {
  if (config[key] === undefined) {
    console.error(`project.json is missing "${key}"`)
    process.exit(1)
  }
}
const CACHE_MS = Math.max(0, Number(config.cacheSeconds ?? 30)) * 1000
// CI (ci_status, merge_when_green): which workflows hold the required checks, the issue that lists
// known intermittent failures, and how long merge_when_green may wait.
const CI = {
  workflows: config.ci?.workflows ?? ['.github/workflows/build.yml'],
  knownFailures: config.ci?.knownFailuresIssue ?? null,
  waitMinutes: Number(config.ci?.waitMinutes ?? 40),
  // PROJECT_BOARD_CI_POLL_MS: for the tests only, which cannot wait 30 s between polls
  pollMs: Number(process.env.PROJECT_BOARD_CI_POLL_MS) || Number(config.ci?.pollSeconds ?? 30) * 1000,
}

// --- The short cache -------------------------------------------------------------------------------
// One board in memory, for at most CACHE_MS. A write forgets it, and a read that started before a
// write never refills it (the generation check), so a tool never answers from a board older than
// its own last write.
let cache = null
let generation = 0
let inflight = null

async function board({ fresh = false } = {}) {
  if (!fresh && cache && cache.generation === generation && Date.now() - cache.at < CACHE_MS) return cache.board
  if (inflight && inflight.generation === generation) return inflight.promise
  const started = generation
  const promise = readBoard(config).then((b) => {
    if (started === generation) cache = { board: b, at: Date.now(), generation: started }
    return b
  })
  inflight = { generation: started, promise }
  promise.finally(() => {
    if (inflight?.promise === promise) inflight = null
  }).catch(() => {})
  return promise
}
const forget = () => {
  generation += 1
  cache = null
}

// --- One write at a time ---------------------------------------------------------------------------
// An agent may send several calls at once (a live Claude session sent both halves of a round trip
// in parallel). Each write reads the item fresh, so running them in arrival order keeps every
// "from → to" true and the last call the one that wins. A batch is one call: its items run in the
// order given, and no other write runs in between.
let writes = Promise.resolve()
function oneAtATime(fn) {
  const run = writes.then(fn, fn)
  writes = run.catch(() => {})
  return run
}

// --- Presenting ------------------------------------------------------------------------------------
// What the model reads is short: one line per item, and the same words in the text and in
// structuredContent (docs/apps.md §9.2: Claude Code hands the model the structured part, not the
// text). URLs and ids only when `detail: "full"` asks for them.
const FIELDS = ['status', 'priority', 'area']
const TYPE = { issue: 'issue', pull: 'pull request', draft: 'draft issue', hidden: 'hidden item' }
const refOf = (repo, number) => (sameRepo(repo, config.repository) ? `#${number}` : `${repo}#${number}`)
const ref = (item) => (item.number == null ? TYPE[item.type] : refOf(item.repository, item.number))
const label = (item) => `${ref(item)} ${item.title}`
const none = (v) => v ?? '(none)'
/** `#113 Narrow-window reading — Needs decision · Medium · UI`; a pull request says so. */
const line = (item) =>
  `${label(item)}${item.type === 'pull' ? (item.draft ? ' (draft PR)' : ' (PR)') : ''} — ${none(item.status)} · ${none(item.priority)} · ${none(item.area)}`
const fullLine = (item) =>
  `${line(item)} · ${TYPE[item.type]}${item.state ? ` ${item.state.toLowerCase()}` : ''}${item.url ? ` · ${item.url}` : ''} · item ${item.itemId}`

/** Status columns in the project's own order, with the decision column first. */
function columns(b) {
  const names = b.fields.status.options.map((o) => o.name)
  const first = names.find((n) => n.toLowerCase() === String(config.decisionStatus).toLowerCase())
  return first ? [first, ...names.filter((n) => n !== first)] : names
}
const where = (b) => `${b.project.title} (GitHub Project #${b.project.number} of ${b.project.owner}), read from GitHub at ${b.fetchedAt}`
const RANK = { High: 0, Medium: 1, Low: 2 }
const byPriority = (a, b) => (RANK[a.priority] ?? 3) - (RANK[b.priority] ?? 3) || (a.number ?? 0) - (b.number ?? 0)

/**
 * One answer: the text, and the same words first in structuredContent (`summary`). A session's
 * client may hand the model the structured part instead of the text (Claude Code does, seen in a
 * live session), and what a write changed must reach the model either way.
 */
const answer = (t, structured, summary = t) => ({ content: [{ type: 'text', text: t }], structuredContent: { summary, ...structured } })

/**
 * An answer made of a summary and lists of lines. The text is the summary, then each list's lines
 * (under its heading, if it has one; an `inline` list is one line after its heading), so it says
 * exactly what the structured part says.
 */
function linesAnswer(summary, lists, extra = {}) {
  const structured = {}
  const text = [summary]
  for (const [key, heading, lines, inline] of lists) {
    if (!lines.length) continue
    structured[key] = lines
    if (inline) text.push(`${heading} ${lines.join(', ')}.`)
    else text.push(...(heading ? [heading] : []), ...lines)
  }
  return answer(text.join('\n'), { ...structured, ...extra }, summary)
}

/** A failure as an answer: the message says what happened and what to do, and nothing changed. */
function failure(e, prefix = '') {
  const message = `${prefix}${reason(e)}`
  return { isError: true, ...answer(message, { error: { kind: e instanceof GitHubError ? e.kind : 'internal', message } }) }
}
function reason(e) {
  if (e instanceof GitHubError) return e.message
  console.error(e)
  return `Unexpected error: ${e?.message ?? e}`
}

// --- Reading items by number ------------------------------------------------------------------------
const itemRef = z.union([z.string(), z.number()])
const REF_HELP = '8, "#8", "owner/repo#8" or its URL'
const detailInput = z.enum(['compact', 'full']).optional().describe('"full" adds type, state, URL and ids; default "compact"')

const matches = (want) => (i) => i.number === want.number && sameRepo(i.repository, want.repo)

/**
 * Finds the items asked for, in the order asked, once each. A reference that is not an issue or pull
 * request fails the whole read (the model sent something wrong); one that is not in the project is
 * named in `missing`.
 */
function pick(b, inputs) {
  const found = []
  const missing = []
  const seen = new Set()
  for (const input of inputs) {
    const want = parseItemRef(input, config.repository)
    const key = `${want.repo.toLowerCase()}#${want.number}`
    if (seen.has(key)) continue
    seen.add(key)
    const item = b.items.find(matches(want))
    if (item) found.push(item)
    else missing.push(refOf(want.repo, want.number))
  }
  return { found, missing }
}

/** The read tools' answer: compact lines, or with `full` the whole items and where they came from. */
function itemsAnswer(b, summary, items, detail, extra = []) {
  const full = detail === 'full'
  const lists = [['items', '', items.map(full ? fullLine : line)], ...extra]
  if (!full) return linesAnswer(summary, lists)
  const a = linesAnswer(`${summary} ${where(b)}.`, lists, { project: b.project, fetchedAt: b.fetchedAt })
  a.structuredContent.items = items
  return a
}

// --- Writing: one item or a batch -------------------------------------------------------------------
const fieldInputs = {
  status: z.string().optional().describe('Status, for example "Ready" or "In review"'),
  priority: z.string().optional().describe('Priority: High, Medium or Low'),
  area: z.string().optional().describe('Area, for example "UI" or "Apps"'),
}
const batchInputs = (verb) => ({
  item: itemRef.optional().describe(`One issue or pull request: ${REF_HELP}`),
  items: z
    .array(z.union([itemRef, z.object({ item: itemRef, ...fieldInputs })]))
    .min(1)
    .max(50)
    .optional()
    .describe(`Several, ${verb} in this order: each ${REF_HELP}, or { item, status?, priority?, area? }`),
  ...fieldInputs,
})

// Failures after which the next items would fail the same way: stop there instead of repeating it.
const STOPS = new Set(['network', 'auth', 'scope', 'gh-missing', 'setup', 'forbidden', 'internal'])
const stops = (e) => STOPS.has(e instanceof GitHubError ? e.kind : 'internal')

/**
 * Turns `item` or `items` (plus the top-level fields, which apply to every entry that does not set
 * its own) into a list of entries, and checks every reference and option name before anything is
 * written: one wrong name changes nothing, and the answer says each problem once.
 */
function plan(b, { item, items, status, priority, area }, { needFields }) {
  if (item !== undefined && items !== undefined) throw new GitHubError('input', 'Give item (one) or items (a list), not both. Nothing changed.')
  if (item === undefined && items === undefined) throw new GitHubError('input', 'Give item (one) or items (a list). Nothing changed.')
  const shared = { status, priority, area }
  const problems = []
  const entries = (items ?? [item]).map((raw) => {
    const e = raw !== null && typeof raw === 'object' ? raw : { item: raw }
    const entry = { input: e.item, options: {} }
    try {
      entry.want = parseItemRef(e.item, config.repository)
      entry.ref = refOf(entry.want.repo, entry.want.number)
    } catch (err) {
      problems.push(err.message)
      return entry
    }
    let any = false
    for (const key of FIELDS) {
      const value = e[key] ?? shared[key]
      if (value === undefined) continue
      any = true
      try {
        entry.options[key] = resolveOption(b.fields[key], value)
      } catch (err) {
        problems.push(err.message)
      }
    }
    if (needFields && !any) problems.push(`Nothing to change for ${entry.ref}: give status, priority or area.`)
    return entry
  })
  if (problems.length) throw new GitHubError('input', `${[...new Set(problems)].join(' ')} Nothing changed.`)
  return entries
}

const change = (d) => `${d.field} ${none(d.from)} → ${d.to}`

/**
 * Applies the planned options to one item, one field at a time, skipping a field that already has
 * the value. `item` is this batch's own copy, updated after each write so a later entry for the
 * same item starts from the truth. A failed write carries what was done.
 */
async function writeFields(b, item, options) {
  const done = []
  const same = []
  for (const key of FIELDS) {
    const option = options[key]
    if (!option) continue
    const field = b.fields[key].name
    if (item[key] === option.name) {
      same.push(`${field} already ${option.name}`)
      continue
    }
    try {
      await setOption(b.project.id, item.itemId, b.fields[key].id, option.id)
    } catch (e) {
      e.done = done
      throw e
    } finally {
      // Whether or not this write landed, the cached board can no longer be trusted.
      forget()
    }
    done.push({ field, from: item[key], to: option.name })
    item[key] = option.name
  }
  return { done, same }
}

/**
 * GitHub can take a moment to list an item that was just added: on 2026-10-04 the read right after
 * `addProjectV2ItemById` came back without it four times in a row, and a second read a few seconds
 * later had it. So a read that looks for items tries a few times, with short waits.
 */
const LIST_WAITS_MS = [0, 500, 1000, 1500, 2000]
async function findFresh(itemIds) {
  let last
  for (const ms of LIST_WAITS_MS) {
    if (ms) await new Promise((r) => setTimeout(r, ms))
    last = await board({ fresh: true })
    if (itemIds.every((id) => last.items.some((i) => i.itemId === id))) break
  }
  return { board: last, byId: new Map(last.items.map((i) => [i.itemId, i])) }
}

/**
 * Reads the touched items again, fresh, once for the whole batch, and adds to each line what
 * GitHub shows when it is not what was set. It never throws: by now something may have been
 * written, and a failed read must not hide that. Returns the summary's last words.
 */
async function readBack(rows) {
  // Only items that answer with a line: a failed one's line already says how far it got.
  const touched = rows.filter((r) => r.line && r.touched)
  if (!touched.length) return ''
  let byId
  try {
    ;({ byId } = await findFresh(touched.map((r) => r.itemId)))
  } catch (e) {
    return ` Reading it back from GitHub failed: ${e?.message ?? e}`
  }
  // A batch may name the same item twice: each field is checked on the last line that set it.
  const last = new Map()
  for (const r of touched) for (const k of FIELDS) if (r.options[k]) last.set(`${r.itemId} ${k}`, r)
  let off = 0
  for (const r of touched) {
    const now = byId.get(r.itemId)
    if (!now) {
      off += 1
      r.line += ' (GitHub did not list it when read back; look again in a moment)'
      continue
    }
    const wrong = FIELDS.filter((k) => last.get(`${r.itemId} ${k}`) === r && now[k] !== r.options[k].name).map((k) => `${r.fieldNames[k]} ${none(now[k])}`)
    if (wrong.length) {
      off += 1
      r.line += ` (but GitHub now shows ${wrong.join(', ')})`
    }
  }
  return off ? ` Read back from GitHub: ${off} differ${off === 1 ? 's' : ''}, see the line${off === 1 ? '' : 's'}.` : ' Read back from GitHub: as set.'
}

const count = (n, word) => (n ? [`${n} ${word}`] : [])

/** The answer of a write: one line per item, the failures, and `isError` only when nothing worked. */
function writeAnswer(b, ok, counts, failed, tail) {
  const summary = `Project ${b.project.title} on GitHub: ${[...counts, ...count(failed.length, 'failed')].join(', ')}.${tail}`
  const a = linesAnswer(summary, [
    ['results', '', ok.map((r) => r.line)],
    ['failed', 'Failed:', failed],
  ])
  return ok.length === 0 && failed.length ? { isError: true, ...a } : a
}

/** Records a failed entry, and when it means the rest would fail too, the entries not tried. */
function fail(failed, entries, i, text, e) {
  failed.push(text)
  if (!stops(e)) return false
  const rest = entries.slice(i + 1).map((x) => x.ref)
  if (rest.length) failed.push(`Not tried after that: ${rest.join(', ')}.`)
  return true
}

const fieldNamesOf = (b) => Object.fromEntries(FIELDS.map((k) => [k, b.fields[k].name]))

// The two writes. Registered below; each runs inside oneAtATime.
async function setItemFields(args) {
  let b, entries
  try {
    b = await board({ fresh: true })
    entries = plan(b, args, { needFields: true })
  } catch (e) {
    return failure(e)
  }
  const items = b.items.map((i) => ({ ...i }))
  const rows = []
  const failed = []
  for (const [i, e] of entries.entries()) {
    const item = items.find(matches(e.want))
    if (!item) {
      failed.push(`${e.ref} is not in the project ${b.project.title}; add it with add_item.`)
      continue
    }
    const row = { itemId: item.itemId, options: e.options, fieldNames: fieldNamesOf(b) }
    try {
      const { done, same } = await writeFields(b, item, e.options)
      row.touched = done.length > 0
      row.line = done.length ? [`${e.ref} ${done.map(change).join(', ')}`, ...same].join('; ') : `${e.ref} unchanged: ${same.join(', ')}`
      rows.push(row)
    } catch (err) {
      const done = err.done ?? []
      if (fail(failed, entries, i, `${e.ref}: ${done.length ? `${done.map(change).join(', ')} done, then ` : ''}${reason(err)}`, err)) break
    }
  }
  const tail = await readBack(rows)
  const ok = rows.filter((r) => r.line)
  return writeAnswer(b, ok, [...count(ok.filter((r) => r.touched).length, 'changed'), ...count(ok.filter((r) => !r.touched).length, 'unchanged')], failed, tail)
}

async function addItem(args) {
  let b, entries
  try {
    b = await board({ fresh: true })
    entries = plan(b, args, { needFields: false })
  } catch (e) {
    return failure(e)
  }
  const rows = []
  const failed = []
  // One holder per project item, shared by every entry that names it: an item is added once, and a
  // later entry's "from" is what an earlier one set.
  const holders = new Map()
  let stopped = null
  // First every add, in order.
  for (const [i, e] of entries.entries()) {
    const key = `${e.want.repo.toLowerCase()}#${e.want.number}`
    const row = { options: e.options, fieldNames: fieldNamesOf(b), head: `${e.ref} already in the project` }
    let holder = holders.get(key)
    if (!holder) {
      const existing = b.items.find(matches(e.want))
      if (existing) holder = { itemId: existing.itemId, item: { ...existing } }
      else {
        try {
          const content = await findContent(e.want.repo, e.want.number)
          if (!content) {
            failed.push(`${e.ref} is not an issue or pull request this GitHub login can see. Nothing added.`)
            continue
          }
          holder = { itemId: await addContent(b.project.id, content.id), added: true }
          forget()
          Object.assign(row, { added: true, touched: true, head: `${e.ref} added: ${content.title}${content.type === 'pull' ? ' (PR)' : ''}` })
        } catch (err) {
          if (fail(failed, entries, i, `${e.ref}: ${reason(err)} Nothing added.`, err)) {
            stopped = 'its fields were not set after the failure above'
            break
          }
          continue
        }
      }
      holders.set(key, holder)
    }
    Object.assign(row, { holder, itemId: holder.itemId })
    rows.push(row)
  }
  // Then the fields, in the same order. A new item's current values come from GitHub, which may
  // list it only a moment later (findFresh), so every "from" is what GitHub had.
  const toSet = rows.filter((r) => Object.keys(r.options).length)
  const unlisted = [...new Set(toSet.map((r) => r.holder))].filter((h) => !h.item)
  if (!stopped && unlisted.length) {
    try {
      const { byId } = await findFresh(unlisted.map((h) => h.itemId))
      for (const h of unlisted) if (byId.has(h.itemId)) h.item = { ...byId.get(h.itemId) }
    } catch (err) {
      stopped = `reading the project back failed, so its fields were not set: ${reason(err)}`
    }
  }
  for (const r of toSet) {
    const why = stopped ?? (r.holder.item ? null : 'GitHub did not list it yet, so its fields were not set; set them with set_item_fields in a moment')
    if (why) {
      r.failed = true
      failed.push(`${r.head}; ${why}.`)
      continue
    }
    try {
      const { done, same } = await writeFields(b, r.holder.item, r.options)
      if (done.length) r.touched = true
      r.line = [r.head, ...(done.length ? [done.map(change).join(', ')] : []), ...same].join('; ')
    } catch (err) {
      const done = err.done ?? []
      r.failed = true
      failed.push(`${r.head}; ${done.length ? `${done.map(change).join(', ')} done, then ` : ''}${reason(err)}`)
      if (stops(err)) stopped = 'its fields were not set after the failure above'
    }
  }
  for (const r of rows) if (!r.line && !r.failed) r.line = r.added ? r.head : `${r.head}, nothing added`
  const tail = await readBack(rows)
  const ok = rows.filter((r) => r.line)
  return writeAnswer(b, ok, [...count(ok.filter((r) => r.added).length, 'added'), ...count(ok.filter((r) => !r.added).length, 'already in the project')], failed, tail)
}

// --- CI: ci_status and merge_when_green -------------------------------------------------------------
// The decisions are pure functions in ci.mjs; this part reads GitHub, asks them, and says the answer
// in a few lines. The rule both tools keep (#386): green means every required check is reported and
// passed. No checks reported, or any still running, is not green.

const MAX_LOGS = 4
const KNOWN_TTL_MS = 5 * 60_000
let known = null

/** The issue listing known intermittent failures (project.json ci.knownFailuresIssue), kept 5 minutes. */
async function knownFailures() {
  if (known && Date.now() - known.at < KNOWN_TTL_MS) return known
  known = { at: Date.now(), ...(await readIssueText(config.repository, CI.knownFailures)) }
  return known
}

const sha7 = (s) => (s ? String(s).slice(0, 7) : '?')

function rowState(r) {
  const c = r.check
  if (r.state === 'missing') return 'not reported yet'
  if (r.state === 'pending') return `pending (${c?.status ?? c?.state ?? 'waiting'})`
  if (r.state === 'failed') return c?.conclusion && c.conclusion !== 'failure' ? `failed (${c.conclusion})` : 'failed'
  return c?.conclusion && c.conclusion !== 'success' ? `passed (${c.conclusion})` : 'passed'
}

/**
 * For each failed check (required first, at most MAX_LOGS logs read): the first failing test line
 * of its job log, the error after it, and whether the known-failures issue quotes it. Whether it is
 * that flake stays the reader's call; the line says what matched.
 */
async function failureDetails(repo, checks) {
  const failed = [...checks.rows, ...checks.others].filter((r) => r.state === 'failed')
  const lines = []
  let issue = null
  let issueError = null
  for (const [i, r] of failed.entries()) {
    const job = r.check?.jobId ?? null
    const head = `${r.name}${checks.rows.includes(r) ? '' : ' (not required)'}${job ? ` (job ${job})` : ''}:`
    if (!job) {
      lines.push(`${head} not a GitHub Actions job, so no log${r.check?.url ? `; see ${r.check.url}` : ''}.`)
      continue
    }
    if (i >= MAX_LOGS) {
      lines.push(`${head} log not read (only the first ${MAX_LOGS} failures are).`)
      continue
    }
    let f
    try {
      f = firstFailure(await readJobLog(repo, job))
    } catch (e) {
      if (e instanceof GitHubError && ['network', 'auth', 'gh-missing'].includes(e.kind)) throw e
      lines.push(`${head} ${reason(e)}`)
      continue
    }
    let tail = ''
    if (CI.knownFailures && sameRepo(repo, config.repository) && (f.line || f.error)) {
      if (!issue && !issueError) {
        try {
          issue = await knownFailures()
        } catch (e) {
          issueError = reason(e)
        }
      }
      const match = issue ? matchKnownFailure(f, issue.text) : null
      if (match) tail = ` | known intermittent failure? #${CI.knownFailures}${issue.state === 'CLOSED' ? ' (closed)' : ''} quotes "${match}"`
      else if (issueError) tail = ` | #${CI.knownFailures} could not be read: ${clip(issueError, 120)}`
    }
    lines.push(`${head} ${f.line ?? 'no failing test line found'}${f.error ? ` | ${f.error}` : ''}${tail}`)
  }
  return lines
}

const VERDICT = {
  green: 'green, every required check reported and passed',
  failing: 'failing',
  pending: 'pending',
  none: 'no checks reported yet, which is not green',
}

/** The CI part of an answer: a summary, then one line per check that is not passed, then failures. */
function ciLines(what, sha, req, checks, failures = []) {
  const c = checks.counts
  const parts = [`${c.passed} of ${c.total} passed`, ...(c.failed ? [`${c.failed} failed`] : []), ...(c.pending ? [`${c.pending} pending`] : []), ...(c.missing ? [`${c.missing} not reported yet`] : [])]
  const summary = `${what} at ${sha7(sha)}: ${VERDICT[checks.verdict]}. Required (${req.source}): ${parts.join(', ')}.`
  const lines = checks.rows.filter((r) => r.state !== 'passed').map((r) => `${r.name}: ${rowState(r)}`)
  const passed = checks.rows.filter((r) => r.state === 'passed').map((r) => r.name)
  if (passed.length) lines.push(`Passed: ${passed.join(', ')}.`)
  if (req.unresolved.length) lines.push(`Could not name the checks of ${req.unresolved.join(', ')}, so every reported check counts as required.`)
  if (checks.others.length) lines.push(`Not required: ${checks.others.map((r) => `${r.name} ${rowState(r)}`).join(', ')}.`)
  return { summary, checks: lines, failures }
}

/** An answer whose text is the summary, the check lines and the failures, as its structured part says. */
function ciAnswer(summary, ci, extra = {}, { isError = false } = {}) {
  const text = [summary, ...ci.checks, ...(ci.failures.length ? ['Failures:', ...ci.failures] : [])]
  const a = answer(text.join('\n'), { ...extra, checks: ci.checks, ...(ci.failures.length ? { failures: ci.failures } : {}) }, summary)
  return isError ? { isError: true, ...a } : a
}

async function evaluate(repo, sha, req) {
  return evaluateChecks({ required: req.names, reported: await readChecks(repo, sha), alsoReported: req.unresolved.length > 0 })
}

async function ciStatus({ pr, ref, repo }) {
  if ((pr === undefined) === (ref === undefined)) throw new GitHubError('input', 'Give pr (a pull request) or ref (a branch, tag or commit), one of them.')
  let what, sha, base, target
  if (pr !== undefined) {
    const want = parseItemRef(pr, config.repository)
    target = want.repo
    const p = await readPr(target, want.number)
    what = `PR ${refOf(target, p.number)}${p.state === 'OPEN' ? '' : ` (${String(p.state).toLowerCase()})`}`
    sha = p.headRefOid
    base = p.baseRefName
  } else {
    target = repo ?? config.repository
    const [r, resolved] = await Promise.all([readRepo(target), resolveRef(target, ref)])
    what = `${sameRepo(target, config.repository) ? '' : `${target} `}${ref}`
    sha = resolved
    base = r.defaultBranch
  }
  const req = await readRequired(target, base, CI.workflows, workflowCheckNames)
  const checks = await evaluate(target, sha, req)
  const ci = ciLines(what, sha, req, checks, await failureDetails(target, checks))
  return ciAnswer(ci.summary, ci, { verdict: checks.verdict, head: sha })
}

/** Sleeps, or stops early when the call is cancelled. Answers false when cancelled. */
function sleep(ms, signal) {
  if (signal?.aborted) return Promise.resolve(false)
  return new Promise((resolve) => {
    const t = setTimeout(() => (signal?.removeEventListener('abort', stop), resolve(true)), ms)
    const stop = () => (clearTimeout(t), resolve(false))
    signal?.addEventListener('abort', stop, { once: true })
  })
}

/**
 * Tells the caller the call is alive. Centralu ends a call after 10 minutes without progress
 * (docs/apps.md §5), and a wait for CI runs up to 40; the message shows under the session's tool card.
 */
function progress(ctx, n, message) {
  console.error(`[project-board] ${message}`)
  const token = ctx?.mcpReq?._meta?.progressToken
  if (token === undefined || typeof ctx?.mcpReq?.notify !== 'function') return
  void ctx.mcpReq.notify({ method: 'notifications/progress', params: { progressToken: token, progress: n, message } }).catch(() => {})
}

// GitHub works out whether a PR can be merged when asked, within seconds: a few short retries first.
const MERGEABLE_RETRIES = 3
const MERGEABLE_WAIT_MS = 2_000
const span = (ms) => (ms < 120_000 ? `${Math.round(ms / 1000)} s` : `${Math.round(ms / 60_000)} min`)

async function mergeWhenGreen({ pr, body, wait = false, waitMinutes, deleteBranch: del = false }, ctx) {
  const want = parseItemRef(pr, config.repository)
  const repo = want.repo
  const what = `PR ${refOf(repo, want.number)}`
  const refused = (reason, ci, extra = {}) =>
    ci ? ciAnswer(`Not merged: ${reason}`, ci, { outcome: 'refused', merged: false, ...extra }, { isError: true }) : { isError: true, ...answer(`Not merged: ${reason}`, { outcome: 'refused', merged: false, ...extra }) }

  // Who is asking comes first: a contributor's agent gets no further (#386, merge policy).
  const { permissions } = await readRepo(repo)
  if (!canMerge(permissions)) return refused(NO_PERMISSION.reason, null, { kind: 'permission' })

  let p = await readPr(repo, want.number)
  const firstHead = p.headRefOid
  const req = await readRequired(repo, p.baseRefName, CI.workflows, workflowCheckNames)
  const limitMs = Math.min(60, Math.max(0, Number(waitMinutes ?? CI.waitMinutes) || 0)) * 60_000
  const started = Date.now()
  const signal = ctx?.mcpReq?.signal
  let quick = 0
  let beat = 0
  for (;;) {
    const checks = await evaluate(repo, p.headRefOid, req)
    const d = decideMerge({ permissions, pr: p, checks })
    if (d.action === 'refuse') {
      const ci = ciLines(what, p.headRefOid, req, checks, d.kind === 'failing' ? await failureDetails(repo, checks) : [])
      return refused(d.reason, ci, { kind: d.kind, verdict: checks.verdict })
    }
    if (d.action === 'merge') return doMerge(repo, what, p, body, del, ciLines(what, p.headRefOid, req, checks))
    // wait
    let pause = CI.pollMs
    if (d.kind === 'mergeable' && quick < MERGEABLE_RETRIES) {
      quick += 1
      pause = MERGEABLE_WAIT_MS
    } else if (!wait) {
      const ci = ciLines(what, p.headRefOid, req, checks)
      return ciAnswer(`Not merged yet: ${d.reason} Call again later, or with wait: true to wait for them.`, ci, { outcome: 'pending', merged: false, verdict: checks.verdict })
    } else if (Date.now() - started + pause > limitMs) {
      const ci = ciLines(what, p.headRefOid, req, checks)
      return ciAnswer(`Not merged: still not green after ${span(Date.now() - started)} of waiting (limit ${span(limitMs)}). ${d.reason}`, ci, {
        outcome: 'timeout',
        merged: false,
        verdict: checks.verdict,
      })
    } else {
      beat += 1
      progress(ctx, beat, `Waiting for ${what} (${span(Date.now() - started)} so far): ${d.reason}`)
    }
    if (!(await sleep(pause, signal))) return { isError: true, ...answer('Not merged: cancelled while waiting.', { outcome: 'cancelled', merged: false }) }
    p = await readPr(repo, want.number)
    if (p.headRefOid !== firstHead)
      return refused(`its head moved from ${sha7(firstHead)} to ${sha7(p.headRefOid)} while waiting, so the checks waited on are not the ones that count. Call again to wait on the new commit.`, null, { kind: 'moved' })
  }
}

async function doMerge(repo, what, p, body, del, ci) {
  const msg = squashMessage({ number: p.number, title: p.title, body, description: p.body })
  const why = await mergePr(repo, p.number, p.headRefOid, msg.subject, msg.body)
  if (why) return ciAnswer(`Not merged: GitHub refused the merge: ${why}`, ci, { outcome: 'refused', merged: false, kind: 'github' }, { isError: true })
  let commit = null
  try {
    commit = (await readPr(repo, p.number)).mergeCommit?.oid ?? null
  } catch {
    // merged either way; the commit id is a nicety
  }
  const extra = []
  if (del) {
    if (p.isCrossRepository) extra.push(`Branch ${p.headRefName} not deleted: it is in a fork.`)
    else {
      const e = await deleteBranch(repo, p.headRefName)
      extra.push(e ? `Branch ${p.headRefName} not deleted: ${e}` : `Deleted branch ${p.headRefName}.`)
    }
  }
  const summary = `Merged ${what} (squash) as ${sha7(commit)}: "${msg.subject}".${extra.length ? ` ${extra.join(' ')}` : ''}`
  return ciAnswer(summary, ci, { outcome: 'merged', merged: true, commit, subject: msg.subject })
}

serveStdio(() => {
  const server = new McpServer({ name: 'project-board', version: '0.3.0' }, { capabilities: { tools: {}, resources: {} } })

  centralu.uiResource(server, 'board', UI, new URL('./ui/index.html', import.meta.url))

  // The home tool: the screen's whole state, read from GitHub. It answers a failure as data rather
  // than isError, so the screen states the reason (GitHub unreachable, gh missing, scope missing)
  // instead of showing an empty board, and an outage is not filed as a bug in the app.
  centralu.tool(
    server,
    'show',
    {
      title: 'Show the board',
      description: 'Open the board and return the project, its Status/Priority/Area options and its items.',
      inputSchema: z.object({ refresh: z.boolean().optional().describe('Skip the short cache and ask GitHub now') }),
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { ui: { resourceUri: UI, visibility: ['app'] } },
    },
    async ({ refresh }) => {
      try {
        const b = await board({ fresh: refresh === true })
        return answer(`${b.items.length} items. ${where(b)}.`, {
          ok: true,
          project: b.project,
          columns: columns(b),
          decisionStatus: config.decisionStatus,
          options: { status: b.fields.status.options.map((o) => o.name), priority: b.fields.priority.options.map((o) => o.name), area: b.fields.area.options.map((o) => o.name) },
          items: b.items,
          fetchedAt: b.fetchedAt,
        })
      } catch (e) {
        const f = failure(e)
        return { content: f.content, structuredContent: { ok: false, ...f.structuredContent } }
      }
    },
  )

  centralu.tool(
    server,
    'list_items',
    {
      title: 'List project items',
      description:
        'List the Centralu GitHub Project, one line per item: "#number title — Status · Priority · Area", in board order (decision column first, then by priority). The summary counts every Status. Filter by status, area, priority, or numbers (then in the order given).',
      inputSchema: z.object({
        status: z.string().optional().describe('Only this Status, for example "Ready"'),
        area: z.string().optional().describe('Only this Area, for example "UI"'),
        priority: z.string().optional().describe('Only this Priority: High, Medium or Low'),
        numbers: z.array(itemRef).max(100).optional().describe(`Only these items: each ${REF_HELP}`),
        detail: detailInput,
      }),
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ status, area, priority, numbers, detail }) => {
      try {
        const b = await board()
        const want = {
          status: status === undefined ? null : resolveOption(b.fields.status, status).name,
          area: area === undefined ? null : resolveOption(b.fields.area, area).name,
          priority: priority === undefined ? null : resolveOption(b.fields.priority, priority).name,
        }
        const fits = (i) => (!want.status || i.status === want.status) && (!want.area || i.area === want.area) && (!want.priority || i.priority === want.priority)
        const filters = Object.entries(want).filter(([, v]) => v).map(([k, v]) => `${b.fields[k].name} ${v}`)
        const cols = want.status ? [want.status] : [...columns(b), ...(b.items.some((i) => !i.status) ? [null] : [])]
        let items
        let missing = []
        if (numbers !== undefined) {
          const picked = pick(b, numbers)
          items = picked.found.filter(fits)
          missing = picked.missing
          filters.push(`numbers ${numbers.join(', ')}`)
        } else {
          items = cols.flatMap((c) => b.items.filter((i) => i.status === c && fits(i)).sort(byPriority))
        }
        const counts = cols.map((c) => `${c ?? 'No status'} ${items.filter((i) => i.status === c).length}`)
        const summary = `${b.project.title}: ${items.length} of ${b.items.length} items${filters.length ? `, filtered by ${filters.join(', ')}` : ''}. ${counts.join(' · ')}.`
        return itemsAnswer(b, summary, items, detail, [['missing', 'Not in the project:', missing, true]])
      } catch (e) {
        return failure(e)
      }
    },
  )

  centralu.tool(
    server,
    'get_items',
    {
      title: 'Read specific items',
      description:
        'Read a few items by number, one line each in the order asked: "#number title — Status · Priority · Area". Says which are not in the project.',
      inputSchema: z.object({ items: z.array(itemRef).min(1).max(100).describe(`Each ${REF_HELP}`), detail: detailInput }),
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ items: inputs, detail }) => {
      try {
        const b = await board()
        const { found, missing } = pick(b, inputs)
        const summary = `${b.project.title}: ${found.length} of ${found.length + missing.length} in the project.`
        return itemsAnswer(b, summary, found, detail, [['missing', 'Not in the project:', missing, true]])
      } catch (e) {
        return failure(e)
      }
    },
  )

  centralu.tool(
    server,
    'list_needs_decision',
    {
      title: 'List items that need a decision',
      description: `List the items whose Status is "${config.decisionStatus}" (the owner's pending decisions), highest priority first, one line each. Optionally one Area.`,
      inputSchema: z.object({ area: z.string().optional().describe('Only this Area, for example "UI"'), detail: detailInput }),
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { ui: { visibility: ['model'] } },
    },
    async ({ area, detail }) => {
      try {
        const b = await board()
        const decision = resolveOption(b.fields.status, config.decisionStatus).name
        const wantArea = area === undefined ? null : resolveOption(b.fields.area, area).name
        const items = b.items.filter((i) => i.status === decision && (!wantArea || i.area === wantArea)).sort(byPriority)
        const summary = `${b.project.title}: ${items.length} item${items.length === 1 ? '' : 's'} with Status ${decision}${wantArea ? ` in Area ${wantArea}` : ''}.`
        return itemsAnswer(b, summary, items, detail)
      } catch (e) {
        return failure(e)
      }
    },
  )

  // Writes. Visible to agents and to the screen (the board's status menu and drag call this one), so
  // both go through the same code. Every answer names what changed on GitHub, then checks it.
  centralu.tool(
    server,
    'set_item_fields',
    {
      title: 'Set Status, Priority or Area',
      description:
        'Set Status, Priority and/or Area on GitHub for one project item (item) or several (items, in order). Top-level status/priority/area apply to every entry without its own. Answers one line per item, e.g. "#297 Status Needs decision → Ready", then failures. A wrong option name changes nothing and lists the valid names.',
      inputSchema: z.object(batchInputs('set')),
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    (args) => oneAtATime(() => setItemFields(args)),
  )

  centralu.tool(
    server,
    'add_item',
    {
      title: 'Add issues or pull requests to the project',
      description:
        'Add one issue or pull request (item) or several (items, in order) to the Centralu GitHub Project, optionally setting Status, Priority and Area (top-level values apply to every entry without its own). One already in the project is not added twice. Answers one line per item, then failures.',
      inputSchema: z.object(batchInputs('added')),
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
      _meta: { ui: { visibility: ['model'] } },
    },
    (args) => oneAtATime(() => addItem(args)),
  )

  centralu.tool(
    server,
    'ci_status',
    {
      title: 'CI status of a pull request or commit',
      description:
        'The required checks of a pull request (pr) or a branch, tag or commit (ref), and whether every one is reported and passed. Verdict green, pending, failing, or none (no checks reported, which is not green). The required set comes from branch protection, else the CI workflow jobs on the base branch. For each failed job: the first failing test line of its log, the error after it, and whether the known intermittent failures issue quotes it.',
      inputSchema: z.object({
        pr: itemRef.optional().describe(`A pull request: ${REF_HELP}`),
        ref: z.string().optional().describe('Instead of pr: a branch, tag or commit sha'),
        repo: z.string().optional().describe('With ref: owner/name; default this project\'s repository'),
      }),
      annotations: { readOnlyHint: true, openWorldHint: true },
      _meta: { ui: { visibility: ['model'] } },
    },
    async (args) => {
      try {
        return await ciStatus(args)
      } catch (e) {
        return failure(e)
      }
    },
  )

  centralu.tool(
    server,
    'merge_when_green',
    {
      title: 'Merge a pull request once CI is green',
      description:
        'Squash-merge a pull request only when the gh account has maintain or admin permission, the PR is open and not a draft, every required check is reported and passed (none reported, or any pending, is not green), and GitHub can merge it. Never auto-merge. Subject "Title (#N)"; body from `body` or the PR description\'s Why / What changed / Closes, without Co-Authored-By or "Generated with" lines; the PR author stays the author. Pending: answers at once, or with wait: true polls until green or failed (up to waitMinutes, default 40) and then merges or reports the failure like ci_status.',
      inputSchema: z.object({
        pr: itemRef.describe(`The pull request: ${REF_HELP}`),
        body: z.string().optional().describe('The squash commit body; default a summary of the PR description'),
        wait: z.boolean().optional().describe('Wait for pending checks instead of answering "pending" at once; default false'),
        waitMinutes: z.number().positive().max(60).optional().describe('With wait: how many minutes to wait at most; default 40'),
        deleteBranch: z.boolean().optional().describe('Delete the head branch on GitHub after the merge (never a fork\'s); default false'),
      }),
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
      _meta: { ui: { visibility: ['model'] } },
    },
    async (args, ctx) => {
      try {
        return await mergeWhenGreen(args, ctx)
      } catch (e) {
        return failure(e, 'Not merged: ')
      }
    },
  )

  return server
})
