// {{APP_NAME}} — this app's MCP server. Centralu starts it (`node server.mjs`, stdio) when it is first
// needed and restarts it after the builder's turn when this folder changed.
// Edit this file and ui/index.html freely. Never edit runtime/ (generated by Centralu).
// Read AGENTS.md for the rules.
import { McpServer, serveStdio, z, centralu } from './runtime/centralu-app-runtime.mjs'

const UI = 'ui://{{APP_ID}}/index.html'

// State lives in the server, and is saved in the app's data folder (outside this folder, so it is
// never committed). The screen only shows it. It survives restarts because it is read back here.
const state = await centralu.readJson('state.json', { count: 0 })
const save = () => centralu.writeJson('state.json', state)
const current = () => ({ content: [{ type: 'text', text: `count = ${state.count}` }], structuredContent: { count: state.count } })

serveStdio(() => {
  const server = new McpServer({ name: '{{APP_ID}}', version: '0.1.0' }, { capabilities: { tools: {}, resources: {} } })

  centralu.uiResource(server, 'main-screen', UI, new URL('./ui/index.html', import.meta.url))

  // The home tool (centralu.app.json "home"): Centralu calls it to open the app's screen. It only reads,
  // so it says readOnlyHint: true — the screen calls it on every refresh, and a read must not trigger one.
  centralu.tool(
    server,
    'show',
    {
      title: 'Show the count',
      description: 'Open the screen and return the current count.',
      inputSchema: z.object({}),
      annotations: { readOnlyHint: true },
      _meta: { ui: { resourceUri: UI } },
    },
    async () => current(),
  )

  // Changes state, so it says readOnlyHint: false. Agents and the screen can both call it.
  centralu.tool(
    server,
    'increment',
    {
      title: 'Increment',
      description: 'Add to the count (default 1) and return the new count.',
      inputSchema: z.object({ by: z.number().int().default(1).describe('How much to add') }),
      annotations: { readOnlyHint: false },
    },
    async ({ by }) => {
      state.count += by
      await save()
      return current()
    },
  )

  // Only the screen may call this one (visibility: ['app']); agents never see it.
  centralu.tool(
    server,
    'reset',
    {
      title: 'Reset',
      description: 'Set the count back to 0.',
      inputSchema: z.object({}),
      annotations: { readOnlyHint: false, destructiveHint: true },
      _meta: { ui: { visibility: ['app'] } },
    },
    async () => {
      state.count = 0
      await save()
      return current()
    },
  )

  return server
})
