import { z } from 'zod'

/**
 * A session id — an opaque identifier we generate ourselves (`randomUUID()`).
 *
 * **The reason its shape is pinned down at the protocol level is that this value becomes a path
 * segment** (#94). The attachments folder (`<data>/attachments/<id>/`) and the handoff note
 * (`<data>/handoff/<project id>/<id>.md`) use this string directly as a directory or file name.
 * Back when it was `z.string()`, sending `"../../Documents"` to `agents.deleteSession` returned
 * `{ ok: true }` while deleting that folder two levels above the data folder with
 * `recursive: true`, and `attachments.save` could create a file at any path with any extension
 * the same way. Both were measured.
 *
 * So the question is not "does this path escape somewhere," but **"is this a single segment to
 * begin with?"** Since separators, and names starting with `.`, cannot pass at all, `..` cannot
 * even be expressed — this is stronger than filtering out escaping paths, and a reader can
 * confirm it in one line. (The same logic already exists in `baseName` in `dev-services/fs.ts`:
 * wherever a name is expected, instead of checking for containment, anything that is not a name
 * is rejected outright.)
 *
 * The 128-character cap is one more filter against a value that is not an id at all — a UUID is
 * 36 characters.
 */
const SESSION_ID_RE = /^[A-Za-z0-9_-][A-Za-z0-9._-]{0,127}$/

export const SessionId = z.string().regex(SESSION_ID_RE, 'Not a session id')
export type SessionId = z.infer<typeof SessionId>

/**
 * The same judgment, in places zod cannot reach.
 *
 * The one filter at the boundary is the main defense (docs/protocol.md §4), and this is a
 * second line of defense that whatever **builds a path** sets up for itself. A function that
 * builds a path can be called without ever passing through the protocol (internal calls, or
 * future callers), and without this function there, #94 comes right back.
 */
export function isSessionId(value: string): boolean {
  return SESSION_ID_RE.test(value)
}

/**
 * A project id — pinned to a shape **for the same reason** as the session id (#132).
 *
 * This value also becomes a path segment: a worktree (`<worktree root>/<project id>/<session
 * id>`) and a handoff note (`<data>/handoff/<project id>/<session id>.md`). Back when it was
 * `z.string()`, sending `projectId: "../escaped"` with `worktree: true` to `agents.createSession`
 * created a git worktree and a branch outside the worktree root before it was even asked whether
 * the project was registered, and only failed afterward with "Project not found," leaving both
 * behind (measured).
 *
 * A project id is also generated by us via `randomUUID()` (the only place this happens is
 * `addProject`) — all 7 projects in real usage data were 36-character UUIDs too. So this reuses
 * the session id's judgment as-is: the question is not containment, but **"is this a single
 * segment to begin with?"**
 */
export const ProjectId = z.string().regex(SESSION_ID_RE, 'Not a project id')
export type ProjectId = z.infer<typeof ProjectId>

/** The same judgment, in places zod cannot reach — a second line of defense for whatever builds a path (the same as `isSessionId`) */
export function isProjectId(value: string): boolean {
  return SESSION_ID_RE.test(value)
}

/** A session's state (product-spec FR-12). Urgency is judged by core/session. */
export const SessionState = z.enum(['idle', 'working', 'waiting_approval', 'waiting_input', 'limited', 'error'])
export type SessionState = z.infer<typeof SessionState>

/**
 * **What** a session is doing while it is busy. A different axis from SessionState.
 *
 * The state remains 'working' even while compacting — since nothing is waiting on us, there is
 * no reason to change it, and adding a new state would silently break every piece of code that
 * checks `state === 'working'`. But looking at the screen alone, it is indistinguishable from
 * generating a reply: both just blink a dot. Measured: one manual compaction took 39 seconds,
 * and during that time there was no way to tell whether it was stuck or working.
 */
/**
 * The kind of busy. compacting comes from either tool, reviewing comes from codex's /review (a
 * dedicated RPC). retrying is codex reconnecting on its own after a dropped stream (an `error`
 * notification with `willRetry`, #168): the turn is still alive, so it is not a failure, but a
 * wait of several attempts should not look like an ordinary one.
 */
export const SessionActivity = z.enum(['compacting', 'reviewing', 'retrying'])

/**
 * The goal set on a session (2026-09-07 — claude's `/goal`, and codex's thread/goal/*).
 *
 * This is the union of both tools: objective/status are shared, iterations/reason are claude's
 * (the number of laps and the reason it fell short, judged each time the Stop hook runs — read
 * from the CLI's Stop hook feedback, since its `active_goal` does not reach a headless session), and
 * tokenBudget/tokensUsed are codex's. status carries the tool's own vocabulary as-is — claude
 * only ever has 'active' while a goal is set (achieving it arrives as a null notification), while
 * codex has active, paused, blocked, usageLimited, budgetLimited, complete. Why this is not
 * tightened into an enum: if the protocol broke every time a tool added a new word, that would
 * cost far more than the value of a single badge.
 */
export const SessionGoal = z.object({
  objective: z.string(),
  status: z.string(),
  iterations: z.number().optional(),
  reason: z.string().optional(),
  tokenBudget: z.number().nullable().optional(),
  tokensUsed: z.number().optional(),
})
export type SessionGoal = z.infer<typeof SessionGoal>
export type SessionActivity = z.infer<typeof SessionActivity>

/**
 * One piece of work an agent runs in the background of a session (#290): a subagent, a backgrounded shell command,
 * an MCP task. The adapter maps its tool's own report onto this — Claude's `background_tasks_changed` and task
 * messages, Codex's child threads — and an adapter that cannot see its background work reports nothing rather than
 * guessing.
 *
 *   kind           what it is. A tool's kind that fits none of the first three is `other`; an unknown word from a
 *                  newer host reads as `other` too, instead of failing the whole event
 *   parentCallId   the tool call that started it, when known: Claude's `Agent` or `Bash` tool_use id, Codex's
 *                  `spawnAgent` collab item. For an agent this is also the key of its recorded steps (#222)
 *   ambient        housekeeping the tool itself says is not activity (Claude's flag). Listed, never counted
 *   stopsWithTurn  what interrupting the session's turn does to it, as measured per tool: true stops it, false
 *                  leaves it running, absent means not measured. Claude: a subagent stops, a shell continues;
 *                  Codex: a child agent continues (probe-background-tasks.mts, probe-codex-background.mts)
 *   stoppable      it can be stopped on its own (`agents.stopBackgroundTask`)
 *   status         running while it is in the live set; an ended task keeps how it ended
 */
export const BackgroundTaskKind = z.enum(['agent', 'shell', 'mcp', 'other'])
export type BackgroundTaskKind = z.infer<typeof BackgroundTaskKind>
export const BackgroundTaskStatus = z.enum(['running', 'completed', 'failed', 'stopped'])
export type BackgroundTaskStatus = z.infer<typeof BackgroundTaskStatus>
export const BackgroundTask = z.object({
  id: z.string(),
  kind: BackgroundTaskKind.catch('other'),
  description: z.string(),
  parentCallId: z.string().optional(),
  ambient: z.boolean().optional(),
  stopsWithTurn: z.boolean().optional(),
  stoppable: z.boolean().optional(),
  status: BackgroundTaskStatus.catch('completed').default('running'),
  /** How it ended, in the tool's words (a failure's reason, a stop's cause). Ended tasks only */
  summary: z.string().optional(),
})
export type BackgroundTask = z.infer<typeof BackgroundTask>

/** How many ended tasks a session keeps listed. Enough for one burst of parallel agents, small enough to stay a list */
export const BACKGROUND_ENDED_KEPT = 10

/**
 * The one way a session's task list moves (#290) — the host's manager, the UI's reducer and the mock all call this,
 * so the three cannot drift apart.
 *
 * `live` replaces every running entry (REPLACE semantics: a missed edge cannot leave a stale "running"). `ended`
 * adds tasks that just left, with their status; an ended task stays listed until `clearEnded` or until it is pushed
 * out by newer ones (`BACKGROUND_ENDED_KEPT`). A task that leaves the live set with no `ended` entry simply
 * disappears — the adapter did not say how it ended, and nothing here guesses.
 */
export function applyBackgroundTasks(
  prev: readonly BackgroundTask[],
  e: { live: readonly BackgroundTask[]; ended?: readonly BackgroundTask[]; clearEnded?: boolean },
): BackgroundTask[] {
  const live = e.live.map((t) => ({ ...t, status: 'running' as const }))
  const liveIds = new Set(live.map((t) => t.id))
  const fresh = (e.ended ?? []).filter((t) => !liveIds.has(t.id) && t.status !== 'running')
  const freshIds = new Set(fresh.map((t) => t.id))
  const kept = e.clearEnded ? [] : prev.filter((t) => t.status !== 'running' && !liveIds.has(t.id) && !freshIds.has(t.id))
  return [...live, ...[...kept, ...fresh].slice(-BACKGROUND_ENDED_KEPT)]
}

/** The running tasks that count as activity — what the header, the sidebar and the idle check count (ambient excluded) */
export function liveBackgroundTasks(tasks: readonly BackgroundTask[]): BackgroundTask[] {
  return tasks.filter((t) => t.status === 'running' && !t.ambient)
}

/**
 * A tool's identifier — open, not a fixed list.
 *
 * This was `z.enum(['claude', 'codex'])`, which meant every vendor had to be taught to
 * this package before an adapter for it could exist: a third tool could not be added
 * without editing a file two layers away from the only code that knows anything about
 * it. The set of tools is now whatever the host has adapters for, and it travels over
 * the wire rather than being compiled in on both sides.
 */
export const ToolName = z.string().min(1)
export type ToolName = z.infer<typeof ToolName>

/**
 * An app's identifier — an open string rather than a closed list (M4 P-1).
 *
 * The UI used to hold this as a union of exactly one, `'control'`. That was true while there was
 * only one compiled-in app, but an app discovered at runtime (an external app under M4) has a
 * name that cannot be known at build time — a closed union leaves the type with no room to
 * enroll such an app in the roster at all. The same move as opening up `ToolName` above (#74):
 * which apps exist is a fact the host knows, not a fact the compiler knows.
 *
 * The wire was open from the start (`apps.*`'s appId was already `z.string()`). Only the UI's
 * type was closed, so no character or length rule is added here — receiving whatever value
 * arrives now, unchanged, is what keeps behavior the same. The character rule for an external
 * app's id is decided where the manifest is validated (A-1).
 */
export const AppId = z.string()
export type AppId = z.infer<typeof AppId>

/**
 * The largest span, in grid cells, a panel may ask for in either direction (#306). A bound on what is stored and
 * declared, not on what is drawn: the grid clamps a span to the columns and rows it has at the window's size.
 */
export const GRID_SPAN_MAX = 4

/**
 * How many grid cells an app panel spans, columns × rows (#306). A session panel is always 1 × 1. Whole numbers from 1
 * to `GRID_SPAN_MAX`; the grid places a span that does not fit at the largest size that does.
 */
export const GridSpan = z.object({
  cols: z.number().int().min(1).max(GRID_SPAN_MAX),
  rows: z.number().int().min(1).max(GRID_SPAN_MAX),
})
export type GridSpan = z.infer<typeof GridSpan>

/**
 * One panel placed on the grid (#288): a session, or an app.
 *
 * Tagged rather than a bare id, because the grid holds both in one order and a session id and an
 * app id can collide. An app is named by its project and its id, the same pair that identifies it
 * everywhere else (`ExternalAppInfo`): `projectId: null` is a user-folder app, and two projects can
 * each have an app with the same id.
 *
 * The shape says nothing about the host's tables on purpose. The grid is a way of looking, and #82
 * moves the grid's list to the client with the remote mode; a reference made only of the panel's
 * identity is something the client can store as it is.
 *
 * The app id is not checked against the manifest's character rule here: this is a layout entry,
 * never a path or a server name, and an app the grid names that does not exist (deleted, or not
 * listed yet) is simply not drawn. The length cap only keeps a value that is not an id out.
 */
export const GridPanel = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('session'), sessionId: SessionId }),
  z.object({
    kind: z.literal('app'),
    projectId: ProjectId.nullable(),
    appId: AppId.min(1).max(128),
    /**
     * The span the person chose for this placement from the panel's top bar (#306), absent when they have not chosen
     * one. Absent is not 1 × 1: the panel then takes the person's setting for the app, else the app's recommendation,
     * else 1 × 1 (the UI's `resolveGridSpan`). Optional rather than defaulted, because "not chosen" is the value — a
     * default would write a choice nobody made. A host from before #306 strips it, and the panel falls back to the
     * defaults; nothing else changes.
     */
    span: GridSpan.optional(),
  }),
])
export type GridPanel = z.infer<typeof GridPanel>

/**
 * An external app's status (M4 A).
 *
 *   invalid     the manifest is missing or invalid — `error` states why
 *   untrusted   an app in an untrusted project. Discovered and shown in the list, but **never starts**
 *   stopped     startable, but currently down (starts only the first time it is actually needed)
 *   starting    starting up — from when the process comes up until it reports its tool list
 *   running     up and running
 *   crashed     the last startup or run failed (`error` states why). The next time it is needed, it starts again after a backoff
 *   failed      stopped after repeated failures — does not start again before `apps.restart`
 *   unconfirmed an app imported from outside that the person has not turned on yet, or whose `server`/`uses` changed after being turned on (M4 E-3). Like `untrusted`,
 *               it **never starts**, is not attached to any session, and every call to it is rejected — until the person reviews it via `apps.review` and turns it on via `apps.enable`
 */
export const ExternalAppStatus = z.enum(['invalid', 'untrusted', 'unconfirmed', 'stopped', 'starting', 'running', 'crashed', 'failed'])
export type ExternalAppStatus = z.infer<typeof ExternalAppStatus>

/**
 * One discovered external app (M4 A-2). There is one instance per (project, id) — the same id
 * in two different projects means two different apps. `projectId: null` means a user-folder app.
 */
export const ExternalAppInfo = z.object({
  appId: AppId,
  projectId: z.string().nullable(),
  /** The absolute path to the app's folder (a native path — the screen only ever displays it) */
  dir: z.string(),
  name: z.string().nullable(),
  version: z.string().nullable(),
  description: z.string().nullable(),
  home: z.string().nullable(),
  trusted: z.boolean(),
  status: ExternalAppStatus,
  error: z.string().nullable(),
  warnings: z.array(z.string()),
  /**
   * A fingerprint of the app folder read by the running (or most recently running) process —
   * absent if it has never started on this host (M4 C-4).
   *
   * An open screen's HTML belongs to whatever code was running when that screen was opened. When
   * the building session's turn ends and the app restarts on new code (or `check`/Restart starts
   * it with the current files), this value changes, and the screen uses that to know "my HTML is
   * stale." Restarting on the same code (dying and coming back, or waking from idle) does not
   * change it — reopening would show nothing different. Since it carries no meaning of its own,
   * it is only ever compared.
   */
  codeStamp: z.string().optional(),
  /**
   * The time of this app's most recent error bundle (`apps.errors`'s `latest.at`, M4 C-6) —
   * absent if there has been no error since the host started. The screen's error line refetches
   * the bundle when this changes. This cannot be known from the "changed" notification alone: a
   * read-only tool's failure never emits that notification (emitting it would create a loop of
   * the screen refetching and failing again).
   */
  lastErrorAt: z.number().optional(),
  /**
   * The secrets the manifest declares, and whether a value is set on this machine (M4 E, the
   * secrets field) — absent if there is no declaration. **The value never appears here**: since
   * this list is refetched on every broadcast, it only carries what the screen needs to show
   * (whether a field is empty). Setting and clearing a value goes through `apps.setSecret`.
   */
  secrets: z.array(z.object({ name: z.string(), set: z.boolean() })).optional(),
  /**
   * For a user-folder app imported from outside, its provenance (M4 E-3) — where it came from,
   * when, and when the person turned it on (null if not turned on). The host keeps this marker
   * outside the app's own folder. If it has not been turned on, or `server`/`uses` changed after
   * it was, its status is `unconfirmed`.
   */
  imported: z.object({ source: z.string(), at: z.number(), confirmedAt: z.number().nullable() }).optional(),
  /**
   * The span the app recommends for its panel on the grid (#306), from the manifest's `view.span`, already checked and
   * clamped by the host — absent when the manifest has none. Only a default: the person's choice for the placement and
   * their setting for the app both come first, and an app without one stands at 1 × 1 as before.
   */
  span: GridSpan.optional(),
})
export type ExternalAppInfo = z.infer<typeof ExternalAppInfo>

/**
 * What a person sees before turning an app on (M4 E-3) — for an app to import (or an imported
 * app that needs to be asked about again), **what it runs** (`server`), **what it intends to
 * use** (`uses`), which secrets it wants, and which files will be brought in. Anything not
 * carried over (a name starting with a dot, a symlink) is also listed with a reason.
 *
 * `reviewKey` is the key for whatever turning it on binds together (server and uses). It is sent
 * back unchanged when turning the app on, and the host checks it against **that same** manifest
 * — what the person reviewed and what gets turned on have to be the same thing. `changed` states
 * what changed since it was turned on, when this is a re-review (null for a first-time import).
 */
/** The manifest's `uses` — the capabilities the app declares it will use (M4 D). `agent` is either `true` (the person's default agent) or a list of tool names */
export const AppUses = z.object({
  agent: z.union([z.boolean(), z.array(z.string())]).optional(),
  apps: z.array(z.string()).optional(),
  host: z.array(z.string()).optional(),
})
export type AppUses = z.infer<typeof AppUses>

export const AppReview = z.object({
  appId: AppId,
  name: z.string(),
  version: z.string(),
  description: z.string(),
  server: z.object({ command: z.string(), args: z.array(z.string()) }),
  uses: AppUses,
  secrets: z.array(z.string()),
  home: z.string().nullable(),
  viewOrigin: z.enum(['opaque', 'app']),
  files: z.array(z.object({ path: z.string(), bytes: z.number() })),
  totalBytes: z.number(),
  skipped: z.array(z.object({ path: z.string(), why: z.string() })),
  warnings: z.array(z.string()),
  reviewKey: z.string(),
  source: z.string(),
  changed: z
    .object({
      server: z.boolean(),
      uses: z.boolean(),
      was: z.object({
        server: z.object({ command: z.string(), args: z.array(z.string()) }),
        uses: AppUses,
      }),
    })
    .nullable(),
})
export type AppReview = z.infer<typeof AppReview>

/**
 * One run of an external app (M4 A-6) — who called it (a screen, session or app), which tool,
 * and how it ended.
 *
 * The arguments carry **only a summary and a hash**. The raw arguments are kept in `failure`,
 * and only for the most recent handful of failed calls (since the agent fixing the app needs to
 * see the input that failed). A secret value is replaced with `[redacted:name]` everywhere it
 * would otherwise appear.
 */
export const AppRun = z.object({
  id: z.string(),
  projectId: z.string().nullable(),
  appId: AppId,
  /**
   * A record of what (M4 D-6) — `tool` is this app's own tool being called, `broker` is this app
   * asking Centralu for something (`tool` is the name of the broker tool: run_agent, call_app,
   * host_data). One app's history also carries the chain below it (the row for another app it
   * called, the row for the agent it requested) — linked by `parentRunId`.
   */
  kind: z.enum(['tool', 'broker']),
  tool: z.string(),
  callerKind: z.enum(['view', 'session', 'app']),
  callerSessionId: z.string().nullable(),
  parentRunId: z.string().nullable(),
  status: z.enum(['running', 'ok', 'error', 'cancelled', 'rejected']),
  durationMs: z.number().nullable(),
  argsDigest: z.string(),
  argsSummary: z.string(),
  error: z.string().nullable(),
  createdAt: z.number(),
  /** The agent session run_agent stood up (M4 D-6) — the run history panel's link to jump to that session. Null before the session stands up, and for any other row */
  sessionId: z.string().nullable(),
  /** The tokens for a run_agent row (M4 D-5) — the input/output the tool reported. Null for other rows, and for a run the tool never reported */
  tokens: z.object({ input: z.number(), output: z.number() }).nullable(),
  failure: z.object({ args: z.string(), result: z.string().nullable() }).nullable(),
})
export type AppRun = z.infer<typeof AppRun>

/**
 * An external app's error bundle (M4 C-6) — holds that moment as one unit, whether the app
 * failed to start (start), ended without warning (crash), or a tool call failed (tool). Used by
 * the app screen when it offers "send to builder." The host **never sends it on its own** — only
 * when the person clicks does the UI send `text` to the building session.
 *
 * The arguments are summary-only, and a secret value is replaced with `[redacted:name]` wherever
 * it would appear in standard error, the reason, or the arguments (the same rule as the run history).
 */
/**
 * A question raised the first time an app tries to use a capability (M4 D-4) — belongs to a
 * chain that **started from a screen**. A question from a chain that started from a session is
 * not here; it stands as that session's own approval card (`ApprovalDetail`'s `capability`).
 *
 * `origin` is the app of the screen that started the chain — the question appears on that app's
 * pinned screen, and the sidebar shows that app's row as "waiting for an answer." The app trying
 * to use the capability (`app`) can be another app that the first one called. Once `expiresAt`
 * passes, the host closes it as a denial.
 */
export const AppQuestion = z.object({
  id: z.string(),
  app: z.object({ appId: AppId, projectId: z.string().nullable(), name: z.string() }),
  capability: z.string(),
  text: z.string(),
  origin: z.object({ appId: AppId, projectId: z.string().nullable() }),
  askedAt: z.number(),
  expiresAt: z.number(),
})
export type AppQuestion = z.infer<typeof AppQuestion>

/**
 * A remembered answer for one app (M4 D-4). If `current` is false, the manifest's `uses`
 * changed afterward — that answer no longer applies, and the next attempt to use that
 * capability asks again.
 */
export const AppPermission = z.object({
  capability: z.string(),
  text: z.string(),
  decision: z.enum(['allow', 'deny']),
  decidedAt: z.number(),
  current: z.boolean(),
})
export type AppPermission = z.infer<typeof AppPermission>

/** Agent use one app requested over a period (M4 D-5) — only counts runs that actually stood up (a rejected request never stood one up) */
export const AgentUse = z.object({
  runs: z.number(),
  /** The sum of time taken by finished runs — a still-running run only counts toward the count */
  durationMs: z.number(),
  /** The sum of tokens across runs the tool reported. Null if none reported any */
  tokens: z.object({ input: z.number(), output: z.number() }).nullable(),
})
export type AgentUse = z.infer<typeof AgentUse>

/** One app's agent use (M4 D-5) — the last day, and the 30 days the record retains */
export const AppUsage = z.object({ day: AgentUse, month: AgentUse })
export type AppUsage = z.infer<typeof AppUsage>

export const AppErrorBundle = z.object({
  kind: z.enum(['start', 'crash', 'tool']),
  at: z.number(),
  message: z.string(),
  /** The last lines of the app's standard error */
  stderr: z.array(z.string()),
  tool: z.string().nullable(),
  args: z.string().nullable(),
  runId: z.string().nullable(),
  /**
   * This failure came from a person's decision (M4 D-4) — the person denied a request (agent,
   * another app, host data) made by this call or a chain below it. The screen reports the
   * decision rather than an app error, and does not offer "send to builder." The place to reverse
   * it is that `app`'s run history panel (Permissions, Forget). Absent from an older host's
   * response — null if not present.
   */
  denied: z
    .object({ appId: AppId, projectId: z.string().nullable(), name: z.string(), capability: z.string(), text: z.string() })
    .nullable()
    .default(null),
  /** Text that can be sent to the building session as-is */
  text: z.string(),
  /**
   * When the person sent this bundle to the building session — null if it was never sent (C-6).
   * Each bundle goes **only once**: the host records it and rejects a second attempt. The screen
   * draws "sent" from this (the same on a reopened screen, and in a different window). Absent
   * from an older host's response — null if not present.
   */
  sentAt: z.number().nullable().default(null),
})
export type AppErrorBundle = z.infer<typeof AppErrorBundle>

/**
 * Everything a screen needs to *present* a tool: its name, its mark, and the two
 * commands that fix a tool that isn't ready.
 *
 * Why the shape lives here. Both sides read it — the host names the tool in its "no
 * record of this conversation" message, and `@cc/agent-host` depends on this package and
 * not on `@cc/core`. This is the only shelf both sides can reach.
 *
 * **Why the values do not.** They used to: a `TOOL_META` record right here held the
 * labels, the glyphs, and the install and login commands for two named vendors. Adding a
 * tool meant editing the shared protocol, which is the opposite of what an adapter is
 * for. Each adapter now carries its own descriptor, and they reach the UI through
 * `agents.detect`.
 *
 * This is presentation, not capability. What a tool can *do* is declared by its adapter
 * (`AdapterCapabilities`, `ModelOption`) and must never be listed here — that split is
 * what keeps a new knob from having to be taught to the UI twice.
 */
export const ToolDescriptor = z.object({
  name: ToolName,
  label: z.string(),
  /** One glyph, because the session chip is 14px square and a word does not fit */
  mark: z.string(),
  install: z.string(),
  login: z.string(),
})
export type ToolDescriptor = z.infer<typeof ToolDescriptor>

/**
 * A descriptor and whether that tool can actually be used on this machine right now.
 *
 * One type rather than two lists to join: the screens that draw a row per tool need both
 * halves at once, and a join done in a component is a join that can be done wrong.
 */
export const ToolStatus = ToolDescriptor.extend({
  installed: z.boolean(),
  loggedIn: z.boolean(),
  detail: z.string(),
})
export type ToolStatus = z.infer<typeof ToolStatus>

/** Permission preset — overrides the CLI's global setting on a per-session basis (validated at M0) */
export const PermissionPreset = z.enum(['safe', 'normal', 'auto'])
export type PermissionPreset = z.infer<typeof PermissionPreset>

export const ApprovalDecision = z.enum(['allow', 'deny', 'always'])
export type ApprovalDecision = z.infer<typeof ApprovalDecision>

/** How one project may reach another (#371): 'delegate' is ask_project (part B), 'apps' another project's app tools (part A) */
export const ProjectConsentKind = z.enum(['delegate', 'apps'])
export type ProjectConsentKind = z.infer<typeof ProjectConsentKind>

export const ApprovalScope = z.enum(['session', 'project'])
export type ApprovalScope = z.infer<typeof ApprovalScope>

/**
 * The detail of an approval request. Adapters normalize a tool's raw format into these three
 * kinds. core/approval looks only at kind to judge whether inline approval from the banner is
 * possible (FR-3).
 *
 * `capability` is a card raised by **the host**, not an adapter (M4 D-4) — an app called by this
 * session is trying to use a capability (running an agent, another app, host data) for the first
 * time. The answer is remembered for this app and this capability (asked again if the manifest's
 * `uses` changes). This is why there is no "always allow" here: whether allowed or denied, a
 * single answer is remembered either way.
 */
export const ApprovalDetail = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('command'), command: z.string(), cwd: z.string() }),
  z.object({
    kind: z.literal('file_edit'),
    path: z.string(),
    diffPreview: z.string(),
    multi: z.boolean().default(false),
  }),
  z.object({ kind: z.literal('other'), raw: z.string() }),
  z.object({
    kind: z.literal('capability'),
    /** The app trying to use the capability — name is from the manifest */
    app: z.object({ appId: AppId, projectId: z.string().nullable(), name: z.string() }),
    /** The capability's name — `agent:<tool>`, `app:<scope>/<app>`, `host:<name>` */
    capability: z.string(),
    /** A single line for a person to read — what it is trying to do ("run an agent (Claude Code) in a new session") */
    text: z.string(),
  }),
  /**
   * One project reaching another (#371) — raised by **the host** in the calling session, the first time a session of
   * `from` asks to reach `to`. `access` says how: 'delegate' starts a session in `to` and gives it a task
   * (ask_project, part B); 'apps' attaches one of `to`'s apps to the caller (part A, with `app` naming it).
   *
   * Unlike `capability`, this one has all three answers: allow once (this call only), always (remembered for this
   * pair and kind, revocable in Settings), deny (not remembered — the next call asks again).
   */
  z.object({
    kind: z.literal('project_access'),
    access: ProjectConsentKind,
    from: z.object({ id: z.string(), name: z.string() }),
    to: z.object({ id: z.string(), name: z.string() }),
    /** One line for a person to read: what the caller wants done there (the task, cut short; or the app's use) */
    text: z.string(),
    app: z.object({ appId: z.string(), name: z.string() }).optional(),
  }),
])
export type ApprovalDetail = z.infer<typeof ApprovalDetail>

/** One remembered "always" from one project to another (#371) — a row of Settings' list, with the names as they are now */
export const ProjectConsent = z.object({
  fromProjectId: z.string(),
  fromName: z.string(),
  toProjectId: z.string(),
  toName: z.string(),
  kind: ProjectConsentKind,
  decidedAt: z.number(),
})
export type ProjectConsent = z.infer<typeof ProjectConsent>

/**
 * Choices an agent presents to a person (AskUserQuestion).
 *
 * **Never truncated.** During dogfooding, this tool call once got cut off partway while flowing
 * through as raw JSON, and everything from the second option onward disappeared — the entire
 * means of answering vanished with it. Unlike an approval (ApprovalDetail), this does not carry
 * a preview — it carries **everything needed to answer**.
 */
export const QuestionOption = z.object({
  label: z.string(),
  description: z.string().default(''),
})
export type QuestionOption = z.infer<typeof QuestionOption>

export const Question = z.object({
  question: z.string(),
  /** A short tag (12 characters or fewer recommended) */
  header: z.string().default(''),
  options: z.array(QuestionOption),
  multiSelect: z.boolean().default(false),
})
export type Question = z.infer<typeof Question>

/** The answer to one question — the chosen labels (several if multiSelect, or the typed text for free input) */
export const QuestionAnswer = z.object({
  question: z.string(),
  answers: z.array(z.string()),
})
export type QuestionAnswer = z.infer<typeof QuestionAnswer>

export const ToolSummary = z.object({
  tool: z.string(),
  /** A one-line summary (the full command, a file path, etc.) */
  title: z.string(),
  /** A read-only tool collapses by default in the UI (FR-3's collapse policy) */
  readOnly: z.boolean().default(false),
  paths: z.array(z.string()).default([]),
})
export type ToolSummary = z.infer<typeof ToolSummary>

/**
 * The tokens reported by a tool (`usage_update`). The three input fields **do not overlap** —
 * the same accounting as the Anthropic API:
 *
 *   inputTokens          input that did not come from cache
 *   cacheReadTokens      input read from cache
 *   cacheCreationTokens  input written to cache
 *
 * So all the input the model actually read is the sum of the three. Codex reports input that
 * came from cache **inside** its input count, so the adapter subtracts it to fit this shape
 * (`codex/normalize.ts`). If the two tools did not carry the same meaning here, whatever sums
 * them up (an app's requested-agent history, M4 D-5) would record a different number depending
 * on the tool.
 */
export const TokenUsage = z.object({
  inputTokens: z.number(),
  outputTokens: z.number(),
  cacheReadTokens: z.number().default(0),
  cacheCreationTokens: z.number().default(0),
  costUsd: z.number().optional(),
})
export type TokenUsage = z.infer<typeof TokenUsage>

/**
 * An adapter's capability declaration — the UI enables or disables features based on this
 * (architecture §6.2).
 *
 * **Anything knowable from whether an optional method exists does not go here.** A flag and the
 * implementation can drift apart: there used to be a listExternal flag, and when it was true but
 * the method did not exist, nothing happened, silently. The answer to "can it do this?" has to
 * be single-sourced — if the method exists, it can. What remains here is only the properties a
 * method cannot express (whether approvals are supported, context accuracy, and so on).
 */
export const AdapterCapabilities = z.object({
  approvals: z.boolean(),
  contextUsage: z.enum(['exact', 'estimate', 'none']),
  resume: z.boolean(),
  autoTitle: z.boolean(),
  attachments: z.array(z.enum(['image', 'file'])).default([]),
  /**
   * The response-length (verbosity) tiers. Empty means this tool has no such knob (#54).
   *
   * Why this is not attached to the model instead: codex's `model/list` does not report
   * verbosity per model (that field is absent from generated/v2/Model.ts — measured). Attaching
   * it to the model would mean inventing it ourselves, which breaks the rule against hardcoding
   * the list. A per-tool property belongs in the adapter's capability declaration.
   */
  verbosities: z.array(z.string()).default([]),
  /**
   * The guarantee that while we hold the handle, **nobody else can write to this conversation**
   * (2026-09-02).
   *
   * True for codex — the app-server puts a writer lock on the thread, and opening it a second
   * time is rejected with "already has an active writer" (the adapter even translates that
   * error). Not true for claude: its conversation file has no lock, so in principle something
   * outside can write to it concurrently.
   *
   * Only on top of this guarantee does the manager stamp "the moment the handle is released
   * equals everything up to here is something I already know" (the skip in
   * syncImportedHistory). Stamping it on a tool without this guarantee would mean anything
   * written from outside while the session was alive never gets pulled in — which is why the
   * default is false.
   */
  exclusiveWriter: z.boolean().default(false),
  /**
   * Whether this tool reports its background work (#290, the `background_tasks` event). Not an optional method:
   * reporting is a stream of events, and nothing else says whether silence means "none running" or "cannot see".
   * The idle check (#297) needs that difference — a session whose background work is invisible is never called idle.
   */
  backgroundTasks: z.boolean().default(false),
})
export type AdapterCapabilities = z.infer<typeof AdapterCapabilities>

export const ProtocolErrorCode = z.enum([
  'adapter_crashed',
  /*
   * Another process holds this conversation (Codex's writer lock), so the session could not be
   * opened. Carried as a code, not a sentence, so the screen can offer "continue in a fork".
   * A lock error that arrives after the adapter already handed the session back (a slow
   * background resume) comes as an event with this code (#168, item 5).
   */
  'conversation_locked',
  'tool_not_installed',
  'not_logged_in',
  'session_not_found',
  'rate_limited',
  'version_mismatch',
  'internal',
])
export type ProtocolErrorCode = z.infer<typeof ProtocolErrorCode>

export const ProtocolError = z.object({
  code: ProtocolErrorCode,
  /** A human-readable description — must be displayable by the UI as-is */
  message: z.string(),
  retryable: z.boolean().default(false),
  data: z.unknown().optional(),
})
export type ProtocolError = z.infer<typeof ProtocolError>

/** The git panel (FR-4) */
export const GitFileStatus = z.object({
  path: z.string(),
  staged: z.boolean(),
  status: z.enum(['M', 'A', 'D', 'R', 'U', '?']),
})
export type GitFileStatus = z.infer<typeof GitFileStatus>

export const GitCommit = z.object({
  sha: z.string(),
  shortSha: z.string(),
  subject: z.string(),
  author: z.string(),
  when: z.number(),
  parents: z.array(z.string()),
  /**
   * The name of the session that made this commit (#50). Known through observation, not a hook
   * — the hash is picked up from the agent's `git commit` tool call and recorded only in our own
   * database. Absent for a commit a person made directly — which is the correct outcome.
   */
  sessionName: z.string().optional(),
})
export type GitCommit = z.infer<typeof GitCommit>

/**
 * An app's versions (M4 E-1). For an app outside git (a user-folder app, including an imported
 * one), these are host-kept snapshots taken every time it starts on changed code (the most
 * recent 5); for a project app, git is the version history, so these are the recent commits that
 * touched that app's folder (read-only — restoring happens through git instead).
 *
 * A snapshot's `current` means the app folder's current code matches that version (the folder
 * fingerprints match). `reason` states why it was taken: `started` (it started on that code),
 * `imported` (as brought in), `before restore` (the code right before a restore).
 */
export const AppSnapshot = z.object({
  id: z.string(),
  at: z.number(),
  files: z.number(),
  bytes: z.number(),
  reason: z.string(),
  current: z.boolean(),
})
export type AppSnapshot = z.infer<typeof AppSnapshot>

export const AppVersions = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('snapshots'), snapshots: z.array(AppSnapshot) }),
  z.object({ kind: z.literal('git'), repo: z.boolean(), commits: z.array(GitCommit) }),
])
export type AppVersions = z.infer<typeof AppVersions>

/**
 * One selectable model.
 *
 * **We never write down this list ourselves.** It carries exactly what the tool reports through
 * its official API (Claude: `supportedModels()`, Codex: `model/list`). Hardcoding it would leave
 * this app silently falling behind every time a new model ships — Fable actually shipped once
 * and could not be selected because it was missing from a hardcoded list.
 *
 * Reasoning effort also arrives attached to the model, since which levels are supported differs
 * by model. Keeping it as a separate flag would give two different answers to "does this model
 * support this," and they could disagree.
 */
export const ModelOption = z.object({
  id: z.string(),
  label: z.string(),
  description: z.string().optional(),
  /** The reasoning efforts this model supports. Empty means this model has no effort selection */
  efforts: z.array(z.string()),
  defaultEffort: z.string().nullable(),
  /**
   * Response-speed tiers (codex's serviceTiers — measured: gpt-5.4+ has exactly one, "Fast, 1.5x
   * speed, increased usage"). Unlike verbosity, model/list reports this **per model**, so it
   * attaches to the model — putting it in the adapter's capability declaration would give two
   * different answers to "can this model do this." The name and description are carried
   * verbatim: the wording that usage costs more is codex's own, and it is accurate.
   */
  tiers: z.array(z.object({ id: z.string(), name: z.string(), description: z.string() })).default([]),
})
export type ModelOption = z.infer<typeof ModelOption>

export const GitBranch = z.object({
  name: z.string(),
  current: z.boolean(),
  remote: z.boolean(),
  upstream: z.string().optional(),
})
export type GitBranch = z.infer<typeof GitBranch>

export const GitDiff = z.object({ diff: z.string(), truncated: z.boolean(), binary: z.boolean() })
export type GitDiff = z.infer<typeof GitDiff>

/**
 * An attachment (FR-13).
 * An image is never put into messages.payload as base64 — it would bloat the database and
 * pollute FTS. The host saves it as a file and only the path is exchanged (m2-plan decision D-1).
 */
export const Attachment = z.object({
  kind: z.enum(['image', 'file']),
  /** A relative path for a file inside the project, or the saved absolute path for a pasted image */
  path: z.string(),
  name: z.string(),
  mime: z.string().optional(),
  bytes: z.number().optional(),
})
export type Attachment = z.infer<typeof Attachment>

/**
 * A prior session the tool itself keeps (outside Centralu — including one created in a terminal).
 *
 * Both the list and the body are read **only through each tool's official API**.
 * ~/.claude/projects/**.jsonl and ~/.codex/sessions/**.jsonl are never parsed directly: that file
 * format is not a documented contract, so it breaks silently when the tool is upgraded. The
 * official API absorbs its own version's storage format differences on its own.
 */
export const ExternalSession = z.object({
  externalId: z.string(),
  tool: ToolName,
  title: z.string(),
  updatedAt: z.number(),
  createdAt: z.number().nullable().default(null),
  branch: z.string().nullable().default(null),
  /** A session already imported into Centralu — keeps the same conversation from being opened twice */
  imported: z.boolean().default(false),
  /**
   * **The id of that session**, if it is already open.
   *
   * A label alone is not enough — this used to just say "already imported" while the click still
   * went through as before, producing the same conversation twice in the list (confirmed by
   * measurement). If this value is present, the UI takes the person to that session instead of
   * creating a new one.
   */
  importedAs: z.string().nullable().default(null),
})
export type ExternalSession = z.infer<typeof ExternalSession>

/**
 * A usage snapshot — **per account** (unrelated to any particular session or directory).
 *
 * Received as an array since the number and names of windows differ by tool:
 *   Claude — session (5 hours), weekly_all, weekly_scoped
 *   Codex  — primary (10080 minutes = weekly), secondary
 * The UI draws this without knowing how many windows there are. Adding a new window never
 * requires a screen change.
 */
export const UsageWindow = z.object({
  id: z.string(),
  label: z.string(),
  /** 0 to 100. How much of the limit has been used */
  percent: z.number(),
  /** When the window resets (ISO). Null if unknown */
  resetsAt: z.string().nullable().default(null),
  /** If this window applies to one specific model only, that model's name */
  scope: z.string().nullable().default(null),
})
export type UsageWindow = z.infer<typeof UsageWindow>

export const UsageSnapshot = z.object({
  plan: z.string().nullable().default(null),
  windows: z.array(UsageWindow).default([]),
  /** Daily tokens. A tool that cannot report this leaves it empty — the UI collapses that row on its own */
  daily: z.array(z.object({ date: z.string(), tokens: z.number() })).default([]),
})
export type UsageSnapshot = z.infer<typeof UsageSnapshot>

/**
 * Where this install stands against the registry (issue #43).
 *
 * **One shape carries both the answer and what we are doing about it.** The check and
 * the update are two steps of one errand ("am I behind, and can I stop being behind"),
 * and the screen shows one line for the whole errand — splitting them would force the
 * UI to stitch two facts back together and to invent what to show when they disagree.
 *
 * The host owns every field here; nothing on this list is decided on the UI side.
 */
export const UpdateStatus = z.object({
  /** The running build's version — `APP_VERSION`, the value this app was built from */
  current: z.string(),
  /**
   * What the registry's `latest` tag points at, or null until a check has succeeded.
   *
   * Null is not "up to date". A check that never reached the network must not read as
   * good news — that mistake is what let #42 hide for a whole release.
   */
  latest: z.string().nullable().default(null),
  /** `latest` outranks `current`, by the comparison the launcher ships (`isNewerVersion`) */
  newer: z.boolean().default(false),
  /** Whether the host re-checks on its own schedule. Settings turns this on and off */
  auto: z.boolean().default(true),
  /**
   * "Apply updates automatically when idle" (#352). Off by default. With it on, the host
   * installs a newer version as soon as a check finds one, and the desktop window applies it
   * (relaunch, then the keeper and host switch) once nothing is busy.
   *
   * Defaults to false so a window attached to an older host that sends no such field reads
   * it as off (protocol.md §4: a field added to a host payload carries a default).
   */
  autoApply: z.boolean().default(false),
  /**
   * What the update is doing right now.
   *
   * `restart_required` is where the host stops: the new version is on disk and the running
   * process is still the old one. The host never replaces the running app itself. What
   * comes next is the window's (#352): "Apply now" relaunches it from the updated bundle, or,
   * with `autoApply`, it does so by itself once no session is working or waiting and no
   * terminal or command is running — never mid-turn.
   */
  phase: z.enum(['idle', 'checking', 'updating', 'restart_required', 'failed']).default('idle'),
  /**
   * Why the last check or update did not work, or null when nothing went wrong.
   *
   * A failed *check* is swallowed everywhere it matters (it never breaks startup and
   * never interrupts) but it is still recorded here, because "Check now" that answers
   * with nothing at all is indistinguishable from a button that does nothing.
   */
  error: z.string().nullable().default(null),
  /** When the last successful check finished (epoch ms), or null if none ever has */
  checkedAt: z.number().nullable().default(null),
})
export type UpdateStatus = z.infer<typeof UpdateStatus>

/**
 * The agent CLIs installed on this machine, and whether sessions move to a newer one by
 * themselves (#297).
 *
 * Every session runs its own agent process, started from the CLI that was installed at the time.
 * An update to `claude` or `codex` reaches a session only when its process starts again, and with
 * the keeper (#280) a process can outlive many app restarts. This is the host's half of noticing:
 * which version is installed now. Which version each session runs is on the session
 * (`SessionInfo.agentVersion`).
 *
 * Owned by the host, like `UpdateStatus`: the host reads the installed versions and the host
 * restarts sessions.
 */
export const AgentVersions = z.object({
  /**
   * The version installed now, by tool name. Null: the tool is not installed, or its version could
   * not be read. A tool missing from the record has not been checked yet.
   */
  installed: z.record(z.string(), z.string().nullable()).default({}),
  /**
   * "Move idle sessions to a newly installed agent CLI" (#297). **On by default** (the owner's
   * decision, 2026-10-05): with it on, a session whose process is older than the installed CLI is
   * restarted on the new one once it is fully idle. The conversation continues through resume.
   *
   * Defaults to true so a window on an older host that sends no such field reads it as the setting
   * a host that never saw it would have (protocol.md §4).
   */
  autoApply: z.boolean().default(true),
  /** When the installed versions were last read (epoch ms), or null if never */
  checkedAt: z.number().nullable().default(null),
})
export type AgentVersions = z.infer<typeof AgentVersions>

/**
 * Preferences about the screen itself — how this person wants the app to behave, as
 * opposed to anything an agent does.
 *
 * **One record rather than a flag per errand.** Every screen preference before this one
 * either lived in the workspace snapshot (which is about *where things are*, not how they
 * behave) or nowhere at all, and the alternative on the table was a `setX` method per
 * toggle, the way `updates.setAuto` does it. That shape stops scaling the second there are
 * three of them: three methods, three handlers, three port members, all to carry booleans
 * that are read together at startup and never separately. This is a record so the next
 * preference costs one field.
 */
export const ThemeMode = z.enum(['dark', 'light', 'system'])
export type ThemeMode = z.infer<typeof ThemeMode>

/**
 * The five steps of the app-wide text size (#312 step 5): the root's CSS zoom factor, with 1 as the
 * default. Why a zoom and not a font size: every text size in the UI is pinned in px, and growing
 * only the text in a narrow grid panel breaks its wrapping first; scaling the whole screen by one
 * factor follows the same rule as the OS's own display scaling (the store's TEXT_SCALES comment).
 */
export const TEXT_SIZES = [0.85, 0.925, 1, 1.1, 1.25] as const

/** The nearest of the five steps — a stored value from another build, or a hand edit, lands on one */
export function nearestTextSize(value: number): number {
  let best: number = TEXT_SIZES[2]
  for (const step of TEXT_SIZES) if (Math.abs(step - value) < Math.abs(best - value)) best = step
  return best
}

/**
 * Where the text size used to live: an index (0..4) into the same five steps, in the workspace
 * snapshot's `textScale`. Read once to move it into the preferences, then never again; anything
 * that is not a number is no text size at all.
 */
export function textSizeFromLegacyStep(step: unknown): number | null {
  if (typeof step !== 'number' || !Number.isFinite(step)) return null
  return TEXT_SIZES[Math.min(TEXT_SIZES.length - 1, Math.max(0, Math.round(step)))]!
}

/** Line height (#312 step 5): a factor on the body and code line heights; `normal` is today's values */
export const LineHeight = z.enum(['compact', 'normal', 'relaxed'])
export type LineHeight = z.infer<typeof LineHeight>

export const UiPreferences = z.object({
  /**
   * Enter writes a newline and ⌘/Ctrl+Enter sends, instead of the other way round.
   *
   * It exists for people who write prompts in paragraphs. Shift+Enter has always made a
   * newline, but reaching for Shift on every line break while Enter sits there ready to
   * send mid-thought means the cost of a slip is a half-written instruction already on its
   * way to an agent — and you cannot unsend it.
   *
   * **Off by default, and that is not timidity.** Enter-sends is what every chat window
   * does, so it is what an unfamiliar hand expects; and for someone already using this app,
   * silently moving send onto a different key would break the one keystroke they use more
   * than any other. A preference that has to be asked for is worse than no preference —
   * a preference that changes under you is worse than both.
   */
  sendWithModifierEnter: z.boolean(),
  /**
   * Which side of the theme the screen shows (#312): always the dark one, always the light one,
   * or whichever the OS is set to. The two sides are chosen separately (`themeDark`,
   * `themeLight`) so that following the OS switches between two themes the person picked,
   * rather than between whatever the app thinks dark and light should be.
   */
  themeMode: ThemeMode,
  /**
   * The theme for the dark side: a preset id (`dark`, …) or a theme file's id. Only the choice
   * lives here; a custom theme itself is a file in the data folder's `themes/` (theme.ts), so it
   * can be edited by hand or by an agent and shared as a file.
   */
  themeDark: z.string().max(80),
  /** The theme for the light side: a preset id (`light`, …) or a theme file's id */
  themeLight: z.string().max(80),
  /**
   * An accent colour, or null for none (the default: the app is achromatic, and brightness is
   * what speaks urgency). When set it colours focus, selection, the working orbit and checked
   * controls — never the signal colour, which stays the one thing reserved for "waiting for you".
   */
  accent: z.string().max(80).nullable(),
  /**
   * The body font, as the person wrote it: one family (`Inter`) or a list (`"IBM Plex Sans", Inter`).
   * Empty is the app's own stack. The app's stack is always appended after it (app/typography.ts),
   * so a font that is not installed, or one without Korean, falls back to what shows today.
   */
  bodyFont: z.string().max(200),
  /** The code font, the same way: terminals, code blocks, paths and readouts. Empty is the app's own stack */
  codeFont: z.string().max(200),
  /** Line height of prose and code blocks. Fixed-row views (the code viewer, the diff, the commit graph) stay as they are */
  lineHeight: LineHeight,
  /**
   * The app-wide text size, one of `TEXT_SIZES` (a zoom factor, 1 = default). It lived in the
   * workspace snapshot as a step index (`textScale`) before #312; it is a way of looking, not a
   * place things are, so it moved here with the rest of Appearance. Any number is accepted and
   * lands on the nearest step, so a value from another build never throws the record away.
   */
  textSize: z.number().transform(nearestTextSize),
  /**
   * Whether ordinary sessions get Centralu's light, read-only tools (#320): their own project's
   * sessions (`read_session`, which lists them when given no id), a search of that project's past
   * conversations (`recall`) and the app guide. **On by default** (owner decision, 2026-10-05) — a
   * session asked "what did the other session do?" should be able to look. Not a screen
   * preference, but this is the one record the person's settings already live in; the host reads
   * it when a session starts and on each call.
   */
  sessionTools: z.boolean(),
})
export type UiPreferences = z.infer<typeof UiPreferences>

/**
 * A change to *some* of them. Whatever is left out keeps the value it had.
 *
 * Writing the whole record back would work today, with one field and one window. It stops
 * working the moment there are several: a screen that loaded before a preference existed
 * would post its own idea of the record and quietly undo the one it never knew about.
 * Saying only what changed cannot do that.
 */
export const UiPreferencesPatch = UiPreferences.partial()
export type UiPreferencesPatch = z.infer<typeof UiPreferencesPatch>

/** What someone who has never opened Settings gets. Each field's reason is on the field. */
export const DEFAULT_UI_PREFERENCES: UiPreferences = {
  sendWithModifierEnter: false,
  themeMode: 'dark',
  themeDark: 'dark',
  themeLight: 'light',
  accent: null,
  bodyFont: '',
  codeFont: '',
  lineHeight: 'normal',
  textSize: 1,
  sessionTools: true,
}

/**
 * Turn whatever was stored into a usable record.
 *
 * **Never throws.** The one thing this must not do is take the app down with it: these are
 * preferences, and a blob that is missing, empty, half-written by an older build or plain
 * corrupt is a reason to fall back to the defaults, not a reason to fail to start. Fields
 * that did not exist when the blob was written fill in from the defaults for the same
 * reason — that is what lets the record grow without a migration.
 */
export function parseUiPreferences(raw: unknown): UiPreferences {
  const out: UiPreferences = { ...DEFAULT_UI_PREFERENCES }
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) return out
  const record = raw as Record<string, unknown>
  /*
   * **Field by field.** Parsing the record as a whole meant one bad field (a theme id an
   * older build wrote differently, say) threw away every other preference with it. Each field
   * falls back on its own.
   */
  for (const key of Object.keys(UiPreferences.shape) as (keyof UiPreferences)[]) {
    if (!(key in record)) continue
    const parsed = UiPreferences.shape[key].safeParse(record[key])
    if (parsed.success) (out as Record<string, unknown>)[key] = parsed.data
  }
  return out
}
