/**
 * Keeps only **the words a person actually typed** out of a loaded conversation.
 *
 * Both tools inject their own system text into a user turn — things like a file the IDE opened, a
 * trace of a slash command, or instructions the harness injected. Measured (while dogfooding): a
 * list title came out as `<system_instruction>You are working inside…`, and a first message came
 * out as `<ide_opened_file>…`. Showing that as-is makes a previous conversation unrecognizable.
 *
 * Rather than dropping the whole thing, **only the block is stripped**: a real user message often
 * follows right after an injected block. It is only dropped entirely if nothing is left after stripping.
 */

/** The wrappers a machine injects into a user turn. Identified by the name of the opening tag */
const INJECTED_TAGS = [
  'system-reminder',
  'system_instruction',
  'ide_opened_file',
  'ide_selection',
  'command-name',
  'command-message',
  'command-args',
  'local-command-stdout',
  'local-command-stderr',
  'user-prompt-submit-hook',
]

const BLOCK = new RegExp(`<(${INJECTED_TAGS.join('|')})\\b[^>]*>[\\s\\S]*?</\\1>`, 'gi')
/** Some are opened without a closing tag — everything from that point on is treated as machine text */
const OPEN_ONLY = new RegExp(`<(${INJECTED_TAGS.join('|')})\\b[^>]*>[\\s\\S]*$`, 'i')
/** Self-closing or standalone tags */
const BARE = new RegExp(`</?(${INJECTED_TAGS.join('|')})\\b[^>]*/?>`, 'gi')

const CAVEAT = /^Caveat: The messages below were generated by the user.*$/gim

/**
 * The person's words that remain after stripping out a machine-injected block.
 * An empty string if nothing is left — the caller drops that line.
 */
export function stripInjectedBlocks(text: string): string {
  return text
    .replace(BLOCK, '')
    .replace(OPEN_ONLY, '')
    .replace(BARE, '')
    .replace(CAVEAT, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

/**
 * A one-line title for use in a list.
 * Only the first line if there are several — what matters in a list is "recognizing which
 * conversation this was."
 */
export function cleanTitle(raw: string, max = 80): string {
  const first = stripInjectedBlocks(raw)
    .split('\n')
    .map((l) => l.trim())
    .find((l) => l.length > 0)
  if (!first) return ''
  return first.length > max ? `${first.slice(0, max - 1)}…` : first
}
