/**
 * 불러온 대화에서 **사람이 실제로 친 말**만 남긴다.
 *
 * 두 도구 모두 사용자 턴에 자기 시스템 텍스트를 끼워 넣는다 —
 * IDE가 연 파일, 슬래시 명령의 흔적, 하네스가 주입한 지시문 같은 것들.
 * 실측(도그푸딩)에서 목록 제목이 `<system_instruction>You are working inside…`로,
 * 첫 대화가 `<ide_opened_file>…`로 나왔다. 그대로 보여주면 이전 대화를 알아볼 수 없다.
 *
 * 통째로 버리지 않고 **블록만 걷어낸다**: 주입된 블록 뒤에 진짜 사용자의 말이
 * 이어지는 경우가 많기 때문이다. 걷어낸 뒤 남는 게 없으면 그때 버린다.
 */

/** 사용자 턴에 기계가 끼워 넣는 래퍼들. 여는 태그 이름으로 판별한다 */
const INJECTED_TAGS = [
  'system-reminder',
  'system_instruction',
  'ide_opened_file',
  'ide_selection',
  'command-name',
  'command-message',
  'command-args',
  'local-command-stdout',
  'local-command-stderr',
  'user-prompt-submit-hook',
]

const BLOCK = new RegExp(`<(${INJECTED_TAGS.join('|')})\\b[^>]*>[\\s\\S]*?</\\1>`, 'gi')
/** 닫는 태그 없이 열린 것도 있다 — 그 줄부터 끝까지 기계 텍스트로 본다 */
const OPEN_ONLY = new RegExp(`<(${INJECTED_TAGS.join('|')})\\b[^>]*>[\\s\\S]*$`, 'i')
/** 자기 닫힘·단독 태그 */
const BARE = new RegExp(`</?(${INJECTED_TAGS.join('|')})\\b[^>]*/?>`, 'gi')

const CAVEAT = /^Caveat: The messages below were generated by the user.*$/gim

/**
 * 기계가 끼워 넣은 블록을 걷어내고 남은 사람의 말.
 * 남는 게 없으면 빈 문자열 — 호출자가 그 줄을 버린다.
 */
export function stripInjectedBlocks(text: string): string {
  return text
    .replace(BLOCK, '')
    .replace(OPEN_ONLY, '')
    .replace(BARE, '')
    .replace(CAVEAT, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

/**
 * 목록에 쓸 한 줄 제목.
 * 여러 줄이면 첫 줄만 — 목록에서 중요한 건 "무슨 대화였는지 알아보는 것"이다.
 */
export function cleanTitle(raw: string, max = 80): string {
  const first = stripInjectedBlocks(raw)
    .split('\n')
    .map((l) => l.trim())
    .find((l) => l.length > 0)
  if (!first) return ''
  return first.length > max ? `${first.slice(0, max - 1)}…` : first
}
