import { describe, expect, it, afterEach } from 'vitest'
import {
  __setSessionApiForTest,
  listClaudeSessions,
  readClaudeHistory,
  UNSUPPORTED as CLAUDE_UNSUPPORTED,
} from './claude/history.js'
import {
  isUnknownMethod,
  threadListToSummaries,
  turnsToHistory,
  UNSUPPORTED as CODEX_UNSUPPORTED,
} from './codex/history.js'
import { cleanTitle, stripInjectedBlocks } from './history-text.js'

/**
 * Loading a previous session only ever reads through **each tool's official API** (parsing a
 * transcript file is forbidden). So there are two things to guard here:
 *   1. that the conversion from the response into a conversation is correct
 *   2. that facing an older tool version backs off **without crashing**, leaving a reason behind
 */

afterEach(() => __setSessionApiForTest(undefined))

describe('claude — SDK listSessions/getSessionMessages', () => {
  it('carries the list into summaries (title priority: user-set -> summary -> first prompt)', async () => {
    __setSessionApiForTest({
      listSessions: async () => [
        { sessionId: 'a', customTitle: 'Refactor', summary: 's', firstPrompt: 'f', lastModified: 1000, gitBranch: 'main' },
        { sessionId: 'b', summary: 'Only a summary is set', lastModified: 2000 },
        { sessionId: 'c', firstPrompt: 'Only the first prompt', lastModified: 3000, createdAt: 500 },
        { sessionId: 'd', lastModified: 4000 },
        { summary: 'Dropped without an id' },
      ],
    })
    const out = await listClaudeSessions('/p', 10)
    expect(out.map((s) => [s.externalId, s.title])).toEqual([
      ['a', 'Refactor'],
      ['b', 'Only a summary is set'],
      ['c', 'Only the first prompt'],
      ['d', 'Untitled session'],
    ])
    expect(out[0]).toMatchObject({ updatedAt: 1000, branch: 'main' })
    expect(out[2]!.createdAt).toBe(500)
  })

  it('keeps only the conversation — drops tool results and keeps only the name of a tool call', async () => {
    __setSessionApiForTest({
      listSessions: async () => [],
      getSessionMessages: async () => [
        { type: 'user', message: { content: [{ type: 'text', text: 'Fix the build' }] } },
        { type: 'assistant', message: { content: [{ type: 'tool_use', name: 'Bash', id: 'x' }] } },
        { type: 'user', message: { content: [{ type: 'tool_result', content: 'exit 0' }] } },
        { type: 'assistant', message: { content: [{ type: 'text', text: 'Fixed it' }] } },
        { type: 'system', message: { content: 'compact boundary' } },
      ],
    })
    expect(await readClaudeHistory('s', '/p', 100)).toEqual([
      { role: 'user', text: 'Fix the build' },
      { role: 'assistant', text: '`Bash`' },
      { role: 'assistant', text: 'Fixed it' },
    ])
  })

  it('strips blocks the tool injected and keeps only the person\'s own words', async () => {
    __setSessionApiForTest({
      listSessions: async () => [],
      getSessionMessages: async () => [
        { type: 'user', message: { content: '<command-name>/clear</command-name>' } },
        { type: 'user', message: { content: '<local-command-stdout>ok</local-command-stdout>' } },
        { type: 'user', message: { content: 'Caveat: The messages below were generated by the user' } },
        { type: 'user', message: { content: '<ide_opened_file>a.ts</ide_opened_file>\n\nTake a look at this too' } },
        { type: 'user', message: { content: 'This is really my message' } },
      ],
    })
    expect(await readClaudeHistory('s', '/p', 100)).toEqual([
      { role: 'user', text: 'Take a look at this too' },
      { role: 'user', text: 'This is really my message' },
    ])
  })

  it('an older SDK (missing the function) leaves a reason instead of throwing', async () => {
    __setSessionApiForTest(null)
    await expect(listClaudeSessions('/p', 10)).rejects.toThrow(CLAUDE_UNSUPPORTED)
    await expect(readClaudeHistory('s', '/p', 10)).rejects.toThrow(CLAUDE_UNSUPPORTED)
  })

  it('does not break even when the response is not an array', async () => {
    __setSessionApiForTest({
      listSessions: async () => null as never,
      getSessionMessages: async () => undefined as never,
    })
    expect(await listClaudeSessions('/p', 10)).toEqual([])
    expect(await readClaudeHistory('s', '/p', 10)).toEqual([])
  })
})

describe('codex — thread/list · thread/read', () => {
  it('carries the thread list into summaries (converts a second-based timestamp to ms)', () => {
    const out = threadListToSummaries(
      [
        { id: 't1', preview: 'Fix the tests', updatedAt: 1_700_000_000, createdAt: 1_699_999_000, cwd: '/p' },
        { id: 't2', recencyAt: 1_700_000_500, cwd: '/p' },
        { id: 't3', preview: 'A different folder', cwd: '/other' }, // Filtered on our side even if the server did not filter it
        { preview: 'No id', cwd: '/p' },
      ],
      '/p',
    )
    expect(out).toEqual([
      { externalId: 't1', title: 'Fix the tests', updatedAt: 1_700_000_000_000, createdAt: 1_699_999_000_000 },
      { externalId: 't2', title: 'Untitled session', updatedAt: 1_700_000_500_000, createdAt: undefined },
    ])
  })

  it('pulls only the person and model words out of turns — an unknown item is silently passed over', () => {
    const out = turnsToHistory(
      [
        {
          startedAt: 1_700_000_000,
          items: [
            { type: 'userMessage', content: [{ type: 'input_text', text: 'Run the tests' }] },
            { type: 'reasoning', summary: [], content: [] },
            { type: 'commandExecution', command: 'pnpm test' },
            { type: 'agentMessage', text: 'All tests passed' },
            { type: 'future_item_type', text: 'does not crash even though it is unknown' },
          ],
        },
      ],
      100,
    )
    expect(out).toEqual([
      { role: 'user', text: 'Run the tests', ts: 1_700_000_000_000 },
      { role: 'assistant', text: 'All tests passed', ts: 1_700_000_000_000 },
    ])
  })

  it('keeps the most recent conversation past the limit (trims the older side)', () => {
    const turns = [
      {
        items: Array.from({ length: 10 }, (_, i) => ({ type: 'agentMessage', text: `m${i}` })),
      },
    ]
    expect(turnsToHistory(turns, 3).map((m) => m.text)).toEqual(['m7', 'm8', 'm9'])
  })

  it('gives an empty conversation when turns is missing or malformed', () => {
    expect(turnsToHistory(undefined, 10)).toEqual([])
    expect(turnsToHistory([null, { items: 'not an array' }], 10)).toEqual([])
    expect(threadListToSummaries(undefined, '/p')).toEqual([])
  })

  it('recognizes an older codex\'s "unknown method" response', () => {
    expect(isUnknownMethod(new Error('Method not found'))).toBe(true)
    expect(isUnknownMethod(new Error('JSON-RPC error -32601'))).toBe(true)
    expect(isUnknownMethod(new Error('unknown method thread/list'))).toBe(true)
    // A real failure must not be hidden as "unsupported" — the user needs to see the actual cause
    expect(isUnknownMethod(new Error('EACCES: permission denied'))).toBe(false)
    expect(CODEX_UNSUPPORTED).toMatch(/update/)
  })
})

describe('stripping injected blocks (measured: a title once came out as <system_instruction>)', () => {
  it('strips only the block and keeps the person\'s words that follow it', () => {
    expect(
      stripInjectedBlocks('<ide_opened_file>The user opened /a/b.ts</ide_opened_file>\n\nFix this file'),
    ).toBe('Fix this file')
    expect(stripInjectedBlocks('before\n<system-reminder>background info</system-reminder>\nafter')).toBe('before\n\nafter')
  })

  it('with no closing tag, treats everything from that point on as machine text', () => {
    expect(stripInjectedBlocks('real question\n<system_instruction>\nYou are working inside…')).toBe('real question')
  })

  it('an empty string once stripped means nothing is left — the caller drops that line', () => {
    expect(stripInjectedBlocks('<command-name>/clear</command-name>')).toBe('')
    expect(stripInjectedBlocks('Caveat: The messages below were generated by the user')).toBe('')
  })

  it('a title keeps only the first line after stripping, and is trimmed if too long', () => {
    expect(cleanTitle('<system_instruction>You are working inside Conductor</system_instruction>\nworktree question')).toBe(
      'worktree question',
    )
    expect(cleanTitle('a'.repeat(200), 10)).toBe(`${'a'.repeat(9)}…`)
    expect(cleanTitle('<command-name>/clear</command-name>')).toBe('')
  })

  it('leaves angle-bracket text the model actually wrote untouched', () => {
    expect(stripInjectedBlocks('<div>this is about code</div>')).toBe('<div>this is about code</div>')
  })
})
