import { describe, expect, it } from 'vitest'
import { readdirSync, readFileSync, statSync } from 'node:fs'

/**
 * 우리 앱 명령의 권한 (#143, 스파이크 S-2).
 *
 * Tauri는 앱 매니페스트가 없으면 **로컬 출처에서 온 앱 명령을 권한 검사 없이 통과시킨다**
 * (tauri 2.11.5 webview/mod.rs `on_message`). 그러면 로컬 출처의 페이지는 어느 창·어느
 * 프레임이든 우리 명령을 모두 부를 수 있고, 막는 것은 실행마다 바뀌는 invoke 키 하나다. 그
 * 키는 틀릴 때마다 Tauri가 표준에러에 그대로 쓴다. 그래서 build.rs가 명령마다 권한을 만들고
 * (`AppManifest::commands`), capabilities/default.json이 그 권한을 창 `main`의 로컬 출처에만
 * 준다. 여기서는 그 셋이 서로, 그리고 화면이 실제로 부르는 명령과 맞는지 본다.
 *
 * - 매니페스트 = `invoke_handler`. 매니페스트에만 있으면 처리기 없는 권한이 생기고, 처리기에만
 *   있으면 권한 없는 명령이 생긴다. 권한 없는 명령은 메인 창에서도 거절된다.
 * - 준 권한 = 화면이 부르는 명령. 더 주면 앱 화면 프레임이 노릴 표면만 넓어지고, 덜 주면
 *   화면이 깨진다.
 * - `remote`가 없다. `remote` 권한은 그 출처의 페이지에 권한을 준다. 앱 화면은 루프백 http의
 *   프레임이라, 127.0.0.1을 덮는 `remote`가 생기면 앱 화면 프레임이 우리 명령을 부른다.
 *
 * 창에서 잰 값은 #143 커밋에 있다. 메인 프레임에서는 12개가 모두 답했다. 루프백 프레임에서는
 * 진짜 키를 쥐어도 `allowed on: [windows: "main", URL: local] … permission: allow-<명령>`으로
 * 거절되었다.
 */

const TAURI = 'apps/desktop/src-tauri'
const url = (p: string) => new URL(`../${p}`, import.meta.url)
const read = (p: string) => readFileSync(url(p), 'utf8')
/** 디렉터리 아래 모든 파일 (그 디렉터리 기준 상대 경로) */
const files = (dir: string) =>
  (readdirSync(url(dir), { recursive: true }) as string[]).filter((f) => statSync(url(`${dir}/${f}`)).isFile()).sort()
/** Rust 주석을 지운다 — 주석 안의 이름이나 괄호가 목록으로 읽히지 않게 */
const stripRustComments = (src: string) => src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '')
/** 명령 이름 → 권한 이름 (tauri-utils 2.9.3 acl/build.rs `autogenerate_command_permissions`) */
const allow = (command: string) => `allow-${command.replaceAll('_', '-')}`

/** lib.rs의 `invoke_handler(tauri::generate_handler![…])`에 적은 명령 */
function registered(): string[] {
  const calls = [...stripRustComments(read(`${TAURI}/src/lib.rs`)).matchAll(/\.invoke_handler\(\s*tauri::generate_handler!\[([^\]]*)\]\s*\)/g)]
  expect(calls, 'lib.rs에 invoke_handler(tauri::generate_handler![…])가 정확히 한 번').toHaveLength(1)
  return calls[0]![1]!.split(',').map((s) => s.trim()).filter(Boolean)
}

/** build.rs의 `AppManifest::new().commands(&[…])`에 적은 명령 */
function manifest(): string[] {
  const code = stripRustComments(read(`${TAURI}/build.rs`))
  // 목록이 있어도 tauri-build에 넘기지 않으면 매니페스트가 아니다
  expect(code).toMatch(/tauri_build::try_build\(/)
  expect(code).toMatch(/\.app_manifest\(/)
  expect(code).not.toMatch(/tauri_build::build\(\)/)
  const lists = [...code.matchAll(/AppManifest::new\(\)\s*\.commands\(\s*&\[([^\]]*)\]\s*\)/g)]
  expect(lists, 'build.rs에 AppManifest::new().commands(&[…])가 정확히 한 번').toHaveLength(1)
  return [...lists[0]![1]!.matchAll(/"([^"]+)"/g)].map((m) => m[1]!)
}

/**
 * 화면이 부르는 앱 명령. `@tauri-apps/api`에 의존하는 패키지는 이 둘뿐이라(아래 시험이 지킨다)
 * `invoke('…')`가 있을 수 있는 곳도 이 둘뿐이다.
 */
const CALLER_DIRS = ['apps/desktop/src', 'packages/platform/src']
function calledFromUi(): string[] {
  const out = new Set<string>()
  for (const dir of CALLER_DIRS) {
    for (const f of files(dir)) {
      if (!/\.tsx?$/.test(f) || /\.test\.tsx?$/.test(f)) continue
      // invoke('x') · invoke<T>('x') · invoke<A<B>>('x')
      for (const m of read(`${dir}/${f}`).matchAll(/\binvoke\s*(?:<(?:[^<>()]|<[^<>()]*>)*>)?\(\s*['"`]([\w-]+)['"`]/g)) out.add(m[1]!)
    }
  }
  return [...out].sort()
}

type Permission = string | { identifier: string }
type Capability = {
  identifier: string
  windows?: string[]
  webviews?: string[]
  local?: boolean
  remote?: unknown
  platforms?: string[]
  permissions: Permission[]
}
const CAP_DIR = `${TAURI}/capabilities`
function capabilities(): [string, Capability][] {
  return files(CAP_DIR).map((f) => [f, JSON.parse(read(`${CAP_DIR}/${f}`)) as Capability])
}
const idOf = (p: Permission) => (typeof p === 'string' ? p : p.identifier)
/** 접두사(`플러그인:`)가 없는 권한이 앱 매니페스트의 것이다 (tauri-utils acl/resolved.rs `get_prefix().unwrap_or(APP_ACL_KEY)`) */
const isAppPermission = (id: string) => !id.includes(':')

/** a에만 있는 것 — 실패 메시지가 무엇이 어긋났는지 이름으로 말하게 */
const minus = (a: string[], b: string[]) => a.filter((x) => !b.includes(x)).sort()
const repeated = (a: string[]) => a.filter((x, i) => a.indexOf(x) !== i)

describe('앱 명령의 권한 (#143)', () => {
  it('매니페스트는 invoke_handler에 등록한 명령과 같다', () => {
    const m = manifest()
    const r = registered()
    expect(repeated(m), '매니페스트에 두 번 적힌 명령').toEqual([])
    expect({ handlerWithoutPermission: minus(r, m), permissionWithoutHandler: minus(m, r) }).toEqual({
      handlerWithoutPermission: [],
      permissionWithoutHandler: [],
    })
  })

  it('권한 파일은 매니페스트 명령마다 하나씩이고, 그 밖의 권한 파일은 없다', () => {
    // build.rs가 빌드마다 다시 쓰는 생성물이지만 커밋한다(Tauri 예제 앱과 같게). 명령을 빼도 옛 파일은
    // 지워지지 않고, `permissions/` 아래 파일은 모두 앱 권한으로 읽힌다.
    const want = manifest().map((c) => `autogenerated/${c}.toml`)
    const have = files(`${TAURI}/permissions`)
    expect({ stray: minus(have, want), missing: minus(want, have) }).toEqual({ stray: [], missing: [] })
  })

  it('화면이 부르는 앱 명령은 모두 등록되어 있다', () => {
    const called = calledFromUi()
    expect(called.length).toBeGreaterThan(0)
    expect({ calledButNotRegistered: minus(called, registered()) }).toEqual({ calledButNotRegistered: [] })
  })

  it('준 앱 권한은 화면이 부르는 명령의 allow-<명령>뿐이다', () => {
    const granted = capabilities().flatMap(([, c]) => c.permissions.map(idOf).filter(isAppPermission))
    const needed = calledFromUi().map(allow)
    expect(repeated(granted), '두 번 준 앱 권한').toEqual([])
    expect({ grantedButNotCalled: minus(granted, needed), calledButNotGranted: minus(needed, granted) }).toEqual({
      grantedButNotCalled: [],
      calledButNotGranted: [],
    })
  })

  it('앱 권한은 창 main의 로컬 출처에만 준다', () => {
    const granting = capabilities().filter(([, c]) => c.permissions.map(idOf).some(isAppPermission))
    expect(granting.length).toBeGreaterThan(0)
    for (const [f, c] of granting) {
      expect(c.windows, f).toEqual(['main'])
      expect(c.webviews ?? [], f).toEqual([])
      expect(c.local, f).not.toBe(false)
      expect(c.remote, f).toBeUndefined()
      expect(c.platforms, `${f}: 플랫폼을 좁히면 그 밖의 OS에서 화면이 깨진다`).toBeUndefined()
    }
  })
})

describe('창 권한의 경계 (S-2)', () => {
  it('어느 capability에도 remote가 없다 — 있으면 그 출처의 앱 화면 프레임이 권한을 얻는다', () => {
    const caps = capabilities()
    expect(caps.length).toBeGreaterThan(0)
    for (const [f, c] of caps) expect(c.remote, f).toBeUndefined()
  })

  it('창·웹뷰를 와일드카드로 고르지 않는다', () => {
    for (const [f, c] of capabilities()) {
      expect([...(c.windows ?? []), ...(c.webviews ?? [])].filter((w) => w.includes('*')), f).toEqual([])
    }
  })

  it('이 시험이 못 보는 capability가 없다 — JSON 파일만, 설정 파일 안에는 없다', () => {
    // tauri-build는 capabilities/ 아래를 재귀로(JSON·JSON5·TOML) 읽고, tauri.conf.json의
    // app.security.capabilities에 적은 것도 쓴다. 이 시험은 여기 JSON 파일만 읽는다.
    expect(files(CAP_DIR).filter((f) => !f.endsWith('.json'))).toEqual([])
    for (const conf of ['tauri.conf.json', 'tauri.linux.conf.json']) {
      const c = JSON.parse(read(`${TAURI}/${conf}`)) as { app?: { security?: { capabilities?: unknown } } }
      expect(c.app?.security?.capabilities, conf).toBeUndefined()
    }
  })

  it('@tauri-apps/api에 의존하는 패키지는 apps/desktop과 packages/platform뿐이다 — 화면 호출을 찾는 범위', () => {
    const deps = (dir: string) => {
      const pkg = JSON.parse(read(`${dir}/package.json`)) as Record<string, Record<string, string> | undefined>
      return { ...pkg.dependencies, ...pkg.devDependencies, ...pkg.peerDependencies }
    }
    const users = ['apps', 'packages']
      .flatMap((root) => readdirSync(url(root)).map((d) => `${root}/${d}`))
      .filter((dir) => {
        try {
          return '@tauri-apps/api' in deps(dir)
        } catch {
          return false // package.json이 없는 디렉터리
        }
      })
    expect(users.sort()).toEqual(['apps/desktop', 'packages/platform'])
    expect(CALLER_DIRS.map((d) => d.replace(/\/src$/, '')).sort()).toEqual(users.sort())
  })
})

/**
 * 플러그인이 여는 권한 (#186, M4 E-4). 앱 명령의 권한은 위에서 화면이 부르는 명령과 맞춰 본다. 플러그인의 권한은 그렇게 맞춰 볼
 * 호출 자리가 없어서(웹뷰의 `@tauri-apps/plugin-*`가 부른다), 준 것을 여기 **이름으로** 적는다. 플러그인을 더하거나 권한을 넓히는
 * 일은 이 목록을 고치는 일이다 — 딥링크 플러그인처럼 웹뷰에 스킴 등록 같은 명령을 여는 것이 조용히 들어오지 않게.
 */
describe('플러그인 권한 (#186)', () => {
  it('준 플러그인 권한은 이 목록뿐이다', () => {
    const granted = capabilities()
      .flatMap(([, c]) => c.permissions.map(idOf))
      .filter((id) => !isAppPermission(id))
      .sort()
    expect(granted).toEqual(
      [
        'core:default',
        'core:window:allow-start-dragging',
        'core:window:allow-set-focus',
        'core:window:allow-show',
        'core:window:allow-unminimize',
        'notification:default',
        'global-shortcut:allow-register',
        'global-shortcut:allow-unregister',
        'global-shortcut:allow-is-registered',
        'dialog:default',
        'opener:default',
      ].sort(),
    )
  })
})

/**
 * 앱 링크 `centralu://app?url=…` (M4 E-4). 스킴은 Info.plist에 하나 등록하고, 링크는 OS의 열기 이벤트(`RunEvent::Opened`)로
 * 받는다. 딥링크 플러그인을 쓰지 않는다: 같은 이벤트를 받는 데 플러그인은 웹뷰에 명령을 더 연다. 웹뷰에 더한 것은 쌓인 링크를
 * 꺼내는 앱 명령 하나(`take_app_links`)이고, 그 권한은 위의 시험들이 다른 명령과 똑같이 맞춰 본다.
 */
describe('앱 링크 (M4 E-4)', () => {
  it('등록한 URL 스킴은 centralu 하나뿐이다', () => {
    const plist = read(`${TAURI}/Info.plist`).replace(/<!--[\s\S]*?-->/g, '')
    const lists = [...plist.matchAll(/<key>CFBundleURLSchemes<\/key>\s*<array>([\s\S]*?)<\/array>/g)]
    const schemes = lists.flatMap((m) => [...m[1]!.matchAll(/<string>([^<]*)<\/string>/g)].map((s) => s[1]))
    expect(schemes).toEqual(['centralu'])
    // 설정 파일에서 따로 plist를 가리키면 이 파일이 아닌 것이 합쳐진다 — 이 시험이 보는 것이 번들에 들어가는 것이어야 한다
    for (const conf of ['tauri.conf.json', 'tauri.linux.conf.json']) {
      const c = JSON.parse(read(`${TAURI}/${conf}`)) as { bundle?: { macOS?: { infoPlist?: unknown } }; plugins?: Record<string, unknown> }
      expect(c.bundle?.macOS?.infoPlist, conf).toBeUndefined()
      expect(c.plugins?.['deep-link'], conf).toBeUndefined()
    }
  })

  it('딥링크 플러그인이 없다 — 의존에도, 권한에도', () => {
    expect(stripRustComments(read(`${TAURI}/Cargo.toml`).replace(/#[^\n]*/g, ''))).not.toMatch(/tauri-plugin-deep-link/)
    for (const dir of ['apps/desktop', 'packages/platform']) {
      expect(read(`${dir}/package.json`), dir).not.toMatch(/plugin-deep-link/)
    }
    for (const [f, c] of capabilities()) expect(c.permissions.map(idOf).filter((id) => id.startsWith('deep-link:')), f).toEqual([])
  })

  it('링크를 꺼내는 명령이 등록되어 있고, 화면이 그것을 부르며, 권한은 창 main에만 있다', () => {
    expect(registered()).toContain('take_app_links')
    expect(calledFromUi()).toContain('take_app_links')
    const granting = capabilities().filter(([, c]) => c.permissions.map(idOf).includes('allow-take-app-links'))
    expect(granting.map(([, c]) => c.windows)).toEqual([['main']])
  })
})
